//*
// Common message types shared across services, queries, and transactions.
// Deduplicated from services.proto, transaction_core.proto, query_response.proto,
// transaction_contents.proto, transaction_response.proto.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file common.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResponseCodeEnum } from "./response_code_pb.js";
import type { AccountID, SignatureMap, TransactionID } from "./basic_types_pb.js";
import type { Duration } from "./duration_pb.js";

/**
 * Describes the file common.proto.
 */
export declare const file_common: GenFile;

/**
 * *
 * A wrapper for signed transaction bytes.
 *
 * @generated from message proto.Transaction
 */
export declare type Transaction = Message<"proto.Transaction"> & {
  /**
   * @generated from field: bytes signedTransactionBytes = 5;
   */
  signedTransactionBytes: Uint8Array;
};

/**
 * Describes the message proto.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
export declare const TransactionSchema: GenMessage<Transaction>;

/**
 * *
 * A transaction response.
 *
 * @generated from message proto.TransactionResponse
 */
export declare type TransactionResponse = Message<"proto.TransactionResponse"> & {
  /**
   * @generated from field: proto.ResponseCodeEnum nodeTransactionPrecheckCode = 1;
   */
  nodeTransactionPrecheckCode: ResponseCodeEnum;

  /**
   * @generated from field: uint64 cost = 2;
   */
  cost: bigint;
};

/**
 * Describes the message proto.TransactionResponse.
 * Use `create(TransactionResponseSchema)` to create a new message.
 */
export declare const TransactionResponseSchema: GenMessage<TransactionResponse>;

/**
 * *
 * A query wrapper.
 *
 * @generated from message proto.Query
 */
export declare type Query = Message<"proto.Query"> & {
  /**
   * @generated from oneof proto.Query.query
   */
  query: {
    /**
     * @generated from field: bytes queryBytes = 100;
     */
    value: Uint8Array;
    case: "queryBytes";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.Query.
 * Use `create(QuerySchema)` to create a new message.
 */
export declare const QuerySchema: GenMessage<Query>;

/**
 * *
 * A response wrapper.
 *
 * @generated from message proto.Response
 */
export declare type Response = Message<"proto.Response"> & {
  /**
   * @generated from oneof proto.Response.response
   */
  response: {
    /**
     * @generated from field: bytes responseBytes = 100;
     */
    value: Uint8Array;
    case: "responseBytes";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export declare const ResponseSchema: GenMessage<Response>;

/**
 * *
 * A query header.
 *
 * @generated from message proto.QueryHeader
 */
export declare type QueryHeader = Message<"proto.QueryHeader"> & {
  /**
   * @generated from field: proto.Transaction payment = 1;
   */
  payment?: Transaction;

  /**
   * @generated from field: proto.ResponseType responseType = 2;
   */
  responseType: ResponseType;
};

/**
 * Describes the message proto.QueryHeader.
 * Use `create(QueryHeaderSchema)` to create a new message.
 */
export declare const QueryHeaderSchema: GenMessage<QueryHeader>;

/**
 * *
 * A response header.
 *
 * @generated from message proto.ResponseHeader
 */
export declare type ResponseHeader = Message<"proto.ResponseHeader"> & {
  /**
   * @generated from field: proto.ResponseCodeEnum nodeTransactionPrecheckCode = 1;
   */
  nodeTransactionPrecheckCode: ResponseCodeEnum;

  /**
   * @generated from field: proto.ResponseType responseType = 2;
   */
  responseType: ResponseType;

  /**
   * @generated from field: uint64 cost = 3;
   */
  cost: bigint;

  /**
   * @generated from field: bytes stateProof = 4;
   */
  stateProof: Uint8Array;
};

/**
 * Describes the message proto.ResponseHeader.
 * Use `create(ResponseHeaderSchema)` to create a new message.
 */
export declare const ResponseHeaderSchema: GenMessage<ResponseHeader>;

/**
 * *
 * Signed transaction.
 *
 * @generated from message proto.SignedTransaction
 */
export declare type SignedTransaction = Message<"proto.SignedTransaction"> & {
  /**
   * @generated from field: bytes bodyBytes = 1;
   */
  bodyBytes: Uint8Array;

  /**
   * @generated from field: proto.SignatureMap sigMap = 2;
   */
  sigMap?: SignatureMap;
};

/**
 * Describes the message proto.SignedTransaction.
 * Use `create(SignedTransactionSchema)` to create a new message.
 */
export declare const SignedTransactionSchema: GenMessage<SignedTransaction>;

/**
 * *
 * Transaction body (minimal, no oneof data).
 *
 * @generated from message proto.TransactionBody
 */
export declare type TransactionBody = Message<"proto.TransactionBody"> & {
  /**
   * @generated from field: proto.TransactionID transactionID = 1;
   */
  transactionID?: TransactionID;

  /**
   * @generated from field: proto.AccountID nodeAccountID = 2;
   */
  nodeAccountID?: AccountID;

  /**
   * @generated from field: uint64 transactionFee = 3;
   */
  transactionFee: bigint;

  /**
   * @generated from field: proto.Duration transactionValidDuration = 4;
   */
  transactionValidDuration?: Duration;

  /**
   * @generated from field: bool generateRecord = 5 [deprecated = true];
   * @deprecated
   */
  generateRecord: boolean;

  /**
   * @generated from field: string memo = 6;
   */
  memo: string;
};

/**
 * Describes the message proto.TransactionBody.
 * Use `create(TransactionBodySchema)` to create a new message.
 */
export declare const TransactionBodySchema: GenMessage<TransactionBody>;

/**
 * *
 * A list of transactions.
 *
 * @generated from message proto.TransactionList
 */
export declare type TransactionList = Message<"proto.TransactionList"> & {
  /**
   * @generated from field: repeated proto.Transaction transaction_list = 1;
   */
  transactionList: Transaction[];
};

/**
 * Describes the message proto.TransactionList.
 * Use `create(TransactionListSchema)` to create a new message.
 */
export declare const TransactionListSchema: GenMessage<TransactionList>;

/**
 * *
 * Response type.
 *
 * @generated from enum proto.ResponseType
 */
export enum ResponseType {
  /**
   * @generated from enum value: ANSWER_ONLY = 0;
   */
  ANSWER_ONLY = 0,

  /**
   * @generated from enum value: ANSWER_STATE_PROOF = 1;
   */
  ANSWER_STATE_PROOF = 1,

  /**
   * @generated from enum value: COST_ANSWER = 2;
   */
  COST_ANSWER = 2,

  /**
   * @generated from enum value: COST_ANSWER_STATE_PROOF = 3;
   */
  COST_ANSWER_STATE_PROOF = 3,
}

/**
 * Describes the enum proto.ResponseType.
 */
export declare const ResponseTypeSchema: GenEnum<ResponseType>;

