//*
// Common message types shared across services, queries, and transactions.
// Deduplicated from services.proto, transaction_core.proto, query_response.proto,
// transaction_contents.proto, transaction_response.proto.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file common.proto (package proto, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_duration } from "./duration_pb.js";
import { file_response_code } from "./response_code_pb.js";

/**
 * Describes the file common.proto.
 */
export const file_common = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SBXByb3RvIi0KC1RyYW5zYWN0aW9uEh4KFnNpZ25lZFRyYW5zYWN0aW9uQnl0ZXMYBSABKAwiYQoTVHJhbnNhY3Rpb25SZXNwb25zZRI8Chtub2RlVHJhbnNhY3Rpb25QcmVjaGVja0NvZGUYASABKA4yFy5wcm90by5SZXNwb25zZUNvZGVFbnVtEgwKBGNvc3QYAiABKAQiJgoFUXVlcnkSFAoKcXVlcnlCeXRlcxhkIAEoDEgAQgcKBXF1ZXJ5Ii8KCFJlc3BvbnNlEhcKDXJlc3BvbnNlQnl0ZXMYZCABKAxIAEIKCghyZXNwb25zZSJdCgtRdWVyeUhlYWRlchIjCgdwYXltZW50GAEgASgLMhIucHJvdG8uVHJhbnNhY3Rpb24SKQoMcmVzcG9uc2VUeXBlGAIgASgOMhMucHJvdG8uUmVzcG9uc2VUeXBlIpsBCg5SZXNwb25zZUhlYWRlchI8Chtub2RlVHJhbnNhY3Rpb25QcmVjaGVja0NvZGUYASABKA4yFy5wcm90by5SZXNwb25zZUNvZGVFbnVtEikKDHJlc3BvbnNlVHlwZRgCIAEoDjITLnByb3RvLlJlc3BvbnNlVHlwZRIMCgRjb3N0GAMgASgEEhIKCnN0YXRlUHJvb2YYBCABKAwiSwoRU2lnbmVkVHJhbnNhY3Rpb24SEQoJYm9keUJ5dGVzGAEgASgMEiMKBnNpZ01hcBgCIAEoCzITLnByb3RvLlNpZ25hdHVyZU1hcCLcAQoPVHJhbnNhY3Rpb25Cb2R5EisKDXRyYW5zYWN0aW9uSUQYASABKAsyFC5wcm90by5UcmFuc2FjdGlvbklEEicKDW5vZGVBY2NvdW50SUQYAiABKAsyEC5wcm90by5BY2NvdW50SUQSFgoOdHJhbnNhY3Rpb25GZWUYAyABKAQSMQoYdHJhbnNhY3Rpb25WYWxpZER1cmF0aW9uGAQgASgLMg8ucHJvdG8uRHVyYXRpb24SGgoOZ2VuZXJhdGVSZWNvcmQYBSABKAhCAhgBEgwKBG1lbW8YBiABKAkiPwoPVHJhbnNhY3Rpb25MaXN0EiwKEHRyYW5zYWN0aW9uX2xpc3QYASADKAsyEi5wcm90by5UcmFuc2FjdGlvbiplCgxSZXNwb25zZVR5cGUSDwoLQU5TV0VSX09OTFkQABIWChJBTlNXRVJfU1RBVEVfUFJPT0YQARIPCgtDT1NUX0FOU1dFUhACEhsKF0NPU1RfQU5TV0VSX1NUQVRFX1BST09GEANCJgoiY29tLmhlZGVyYWhhc2hncmFwaC5hcGkucHJvdG8uamF2YVABYgZwcm90bzM", [file_basic_types, file_timestamp, file_duration, file_response_code]);

/**
 * Describes the message proto.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
export const TransactionSchema = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * Describes the message proto.TransactionResponse.
 * Use `create(TransactionResponseSchema)` to create a new message.
 */
export const TransactionResponseSchema = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * Describes the message proto.Query.
 * Use `create(QuerySchema)` to create a new message.
 */
export const QuerySchema = /*@__PURE__*/
  messageDesc(file_common, 2);

/**
 * Describes the message proto.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export const ResponseSchema = /*@__PURE__*/
  messageDesc(file_common, 3);

/**
 * Describes the message proto.QueryHeader.
 * Use `create(QueryHeaderSchema)` to create a new message.
 */
export const QueryHeaderSchema = /*@__PURE__*/
  messageDesc(file_common, 4);

/**
 * Describes the message proto.ResponseHeader.
 * Use `create(ResponseHeaderSchema)` to create a new message.
 */
export const ResponseHeaderSchema = /*@__PURE__*/
  messageDesc(file_common, 5);

/**
 * Describes the message proto.SignedTransaction.
 * Use `create(SignedTransactionSchema)` to create a new message.
 */
export const SignedTransactionSchema = /*@__PURE__*/
  messageDesc(file_common, 6);

/**
 * Describes the message proto.TransactionBody.
 * Use `create(TransactionBodySchema)` to create a new message.
 */
export const TransactionBodySchema = /*@__PURE__*/
  messageDesc(file_common, 7);

/**
 * Describes the message proto.TransactionList.
 * Use `create(TransactionListSchema)` to create a new message.
 */
export const TransactionListSchema = /*@__PURE__*/
  messageDesc(file_common, 8);

/**
 * Describes the enum proto.ResponseType.
 */
export const ResponseTypeSchema = /*@__PURE__*/
  enumDesc(file_common, 0);

/**
 * *
 * Response type.
 *
 * @generated from enum proto.ResponseType
 */
export const ResponseType = /*@__PURE__*/
  tsEnum(ResponseTypeSchema);

