//*
// Consensus topic info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file consensus_info.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "./timestamp_pb.js";
import type { AccountID, Key, KeyList, TopicID } from "./basic_types_pb.js";
import type { Duration } from "./duration_pb.js";
import type { FixedCustomFee } from "./custom_fees_pb.js";
import type { ResponseHeader } from "./common_pb.js";

/**
 * Describes the file consensus_info.proto.
 */
export declare const file_consensus_info: GenFile;

/**
 * @generated from message proto.ConsensusTopicInfo
 */
export declare type ConsensusTopicInfo = Message<"proto.ConsensusTopicInfo"> & {
  /**
   * @generated from field: string memo = 1;
   */
  memo: string;

  /**
   * @generated from field: bytes runningHash = 2;
   */
  runningHash: Uint8Array;

  /**
   * @generated from field: uint64 sequenceNumber = 3;
   */
  sequenceNumber: bigint;

  /**
   * @generated from field: proto.Timestamp expirationTime = 4;
   */
  expirationTime?: Timestamp;

  /**
   * @generated from field: proto.Key adminKey = 5;
   */
  adminKey?: Key;

  /**
   * @generated from field: proto.Key submitKey = 6;
   */
  submitKey?: Key;

  /**
   * @generated from field: proto.Duration autoRenewPeriod = 7;
   */
  autoRenewPeriod?: Duration;

  /**
   * @generated from field: proto.AccountID autoRenewAccount = 8;
   */
  autoRenewAccount?: AccountID;

  /**
   * @generated from field: string ledger_id = 9;
   */
  ledgerId: string;

  /**
   * @generated from field: repeated proto.FixedCustomFee custom_fees = 10;
   */
  customFees: FixedCustomFee[];

  /**
   * @generated from field: proto.KeyList fee_exempt_key_list = 11;
   */
  feeExemptKeyList?: KeyList;
};

/**
 * Describes the message proto.ConsensusTopicInfo.
 * Use `create(ConsensusTopicInfoSchema)` to create a new message.
 */
export declare const ConsensusTopicInfoSchema: GenMessage<ConsensusTopicInfo>;

/**
 * @generated from message proto.ConsensusGetTopicInfoResponse
 */
export declare type ConsensusGetTopicInfoResponse = Message<"proto.ConsensusGetTopicInfoResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.TopicID topicID = 2;
   */
  topicID?: TopicID;

  /**
   * @generated from field: proto.ConsensusTopicInfo topicInfo = 3;
   */
  topicInfo?: ConsensusTopicInfo;
};

/**
 * Describes the message proto.ConsensusGetTopicInfoResponse.
 * Use `create(ConsensusGetTopicInfoResponseSchema)` to create a new message.
 */
export declare const ConsensusGetTopicInfoResponseSchema: GenMessage<ConsensusGetTopicInfoResponse>;

