//*
// Consensus topic info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file consensus_info.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_duration } from "./duration_pb.js";
import { file_response_code } from "./response_code_pb.js";
import { file_custom_fees } from "./custom_fees_pb.js";
import { file_common } from "./common_pb.js";

/**
 * Describes the file consensus_info.proto.
 */
export const file_consensus_info = /*@__PURE__*/
  fileDesc("ChRjb25zZW5zdXNfaW5mby5wcm90bxIFcHJvdG8i+AIKEkNvbnNlbnN1c1RvcGljSW5mbxIMCgRtZW1vGAEgASgJEhMKC3J1bm5pbmdIYXNoGAIgASgMEhYKDnNlcXVlbmNlTnVtYmVyGAMgASgEEigKDmV4cGlyYXRpb25UaW1lGAQgASgLMhAucHJvdG8uVGltZXN0YW1wEhwKCGFkbWluS2V5GAUgASgLMgoucHJvdG8uS2V5Eh0KCXN1Ym1pdEtleRgGIAEoCzIKLnByb3RvLktleRIoCg9hdXRvUmVuZXdQZXJpb2QYByABKAsyDy5wcm90by5EdXJhdGlvbhIqChBhdXRvUmVuZXdBY2NvdW50GAggASgLMhAucHJvdG8uQWNjb3VudElEEhEKCWxlZGdlcl9pZBgJIAEoCRIqCgtjdXN0b21fZmVlcxgKIAMoCzIVLnByb3RvLkZpeGVkQ3VzdG9tRmVlEisKE2ZlZV9leGVtcHRfa2V5X2xpc3QYCyABKAsyDi5wcm90by5LZXlMaXN0IpUBCh1Db25zZW5zdXNHZXRUb3BpY0luZm9SZXNwb25zZRIlCgZoZWFkZXIYASABKAsyFS5wcm90by5SZXNwb25zZUhlYWRlchIfCgd0b3BpY0lEGAIgASgLMg4ucHJvdG8uVG9waWNJRBIsCgl0b3BpY0luZm8YAyABKAsyGS5wcm90by5Db25zZW5zdXNUb3BpY0luZm9CJgoiY29tLmhlZGVyYWhhc2hncmFwaC5hcGkucHJvdG8uamF2YVABYgZwcm90bzM", [file_basic_types, file_timestamp, file_duration, file_response_code, file_custom_fees, file_common]);

/**
 * Describes the message proto.ConsensusTopicInfo.
 * Use `create(ConsensusTopicInfoSchema)` to create a new message.
 */
export const ConsensusTopicInfoSchema = /*@__PURE__*/
  messageDesc(file_consensus_info, 0);

/**
 * Describes the message proto.ConsensusGetTopicInfoResponse.
 * Use `create(ConsensusGetTopicInfoResponseSchema)` to create a new message.
 */
export const ConsensusGetTopicInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_consensus_info, 1);

