//*
// Contract-specific query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file contract_types.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResponseHeader } from "./common_pb.js";
import type { AccountID, ContractID, Key, TokenRelationship } from "./basic_types_pb.js";
import type { Timestamp } from "./timestamp_pb.js";
import type { Duration } from "./duration_pb.js";

/**
 * Describes the file contract_types.proto.
 */
export declare const file_contract_types: GenFile;

/**
 * @generated from message proto.ContractGetInfoResponse
 */
export declare type ContractGetInfoResponse = Message<"proto.ContractGetInfoResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.ContractGetInfoResponse.ContractInfo contractInfo = 2;
   */
  contractInfo?: ContractGetInfoResponse_ContractInfo;
};

/**
 * Describes the message proto.ContractGetInfoResponse.
 * Use `create(ContractGetInfoResponseSchema)` to create a new message.
 */
export declare const ContractGetInfoResponseSchema: GenMessage<ContractGetInfoResponse>;

/**
 * @generated from message proto.ContractGetInfoResponse.ContractInfo
 */
export declare type ContractGetInfoResponse_ContractInfo = Message<"proto.ContractGetInfoResponse.ContractInfo"> & {
  /**
   * @generated from field: proto.ContractID contractID = 1;
   */
  contractID?: ContractID;

  /**
   * @generated from field: proto.AccountID accountID = 2;
   */
  accountID?: AccountID;

  /**
   * @generated from field: string contractAccountID = 3;
   */
  contractAccountID: string;

  /**
   * @generated from field: proto.Timestamp expirationTime = 5;
   */
  expirationTime?: Timestamp;

  /**
   * @generated from field: proto.Duration autoRenewPeriod = 6;
   */
  autoRenewPeriod?: Duration;

  /**
   * @generated from field: int64 storage = 7;
   */
  storage: bigint;

  /**
   * @generated from field: string memo = 8;
   */
  memo: string;

  /**
   * @generated from field: uint64 balance = 9;
   */
  balance: bigint;

  /**
   * @generated from field: bool deleted = 10;
   */
  deleted: boolean;

  /**
   * @generated from field: repeated proto.TokenRelationship tokenRelationships = 11;
   */
  tokenRelationships: TokenRelationship[];

  /**
   * @generated from field: string ledger_id = 12;
   */
  ledgerId: string;

  /**
   * @generated from field: proto.AccountID auto_renew_account_id = 13;
   */
  autoRenewAccountId?: AccountID;

  /**
   * @generated from field: int32 max_automatic_token_associations = 14;
   */
  maxAutomaticTokenAssociations: number;

  /**
   * @generated from field: proto.Key admin_key = 24;
   */
  adminKey?: Key;

  /**
   * @generated from field: proto.AccountID staking_info = 25;
   */
  stakingInfo?: AccountID;
};

/**
 * Describes the message proto.ContractGetInfoResponse.ContractInfo.
 * Use `create(ContractGetInfoResponse_ContractInfoSchema)` to create a new message.
 */
export declare const ContractGetInfoResponse_ContractInfoSchema: GenMessage<ContractGetInfoResponse_ContractInfo>;

/**
 * @generated from message proto.ContractNonceInfo
 */
export declare type ContractNonceInfo = Message<"proto.ContractNonceInfo"> & {
  /**
   * @generated from field: proto.ContractID contract_id = 1;
   */
  contractId?: ContractID;

  /**
   * @generated from field: int64 nonce = 2;
   */
  nonce: bigint;
};

/**
 * Describes the message proto.ContractNonceInfo.
 * Use `create(ContractNonceInfoSchema)` to create a new message.
 */
export declare const ContractNonceInfoSchema: GenMessage<ContractNonceInfo>;

/**
 * @generated from message proto.ContractStateChange
 */
export declare type ContractStateChange = Message<"proto.ContractStateChange"> & {
  /**
   * @generated from field: proto.ContractID contract_id = 1;
   */
  contractId?: ContractID;

  /**
   * @generated from field: repeated proto.StorageChange storage_changes = 2;
   */
  storageChanges: StorageChange[];
};

/**
 * Describes the message proto.ContractStateChange.
 * Use `create(ContractStateChangeSchema)` to create a new message.
 */
export declare const ContractStateChangeSchema: GenMessage<ContractStateChange>;

/**
 * @generated from message proto.StorageChange
 */
export declare type StorageChange = Message<"proto.StorageChange"> & {
  /**
   * @generated from field: bytes slot = 1;
   */
  slot: Uint8Array;

  /**
   * @generated from field: bytes value_read = 2;
   */
  valueRead: Uint8Array;

  /**
   * @generated from field: bytes value_written = 3;
   */
  valueWritten: Uint8Array;
};

/**
 * Describes the message proto.StorageChange.
 * Use `create(StorageChangeSchema)` to create a new message.
 */
export declare const StorageChangeSchema: GenMessage<StorageChange>;

