//*
// Contract-specific query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file contract_types.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_duration } from "./duration_pb.js";
import { file_response_code } from "./response_code_pb.js";
import { file_common } from "./common_pb.js";

/**
 * Describes the file contract_types.proto.
 */
export const file_contract_types = /*@__PURE__*/
  fileDesc("ChRjb250cmFjdF90eXBlcy5wcm90bxIFcHJvdG8i+wQKF0NvbnRyYWN0R2V0SW5mb1Jlc3BvbnNlEiUKBmhlYWRlchgBIAEoCzIVLnByb3RvLlJlc3BvbnNlSGVhZGVyEkEKDGNvbnRyYWN0SW5mbxgCIAEoCzIrLnByb3RvLkNvbnRyYWN0R2V0SW5mb1Jlc3BvbnNlLkNvbnRyYWN0SW5mbxr1AwoMQ29udHJhY3RJbmZvEiUKCmNvbnRyYWN0SUQYASABKAsyES5wcm90by5Db250cmFjdElEEiMKCWFjY291bnRJRBgCIAEoCzIQLnByb3RvLkFjY291bnRJRBIZChFjb250cmFjdEFjY291bnRJRBgDIAEoCRIoCg5leHBpcmF0aW9uVGltZRgFIAEoCzIQLnByb3RvLlRpbWVzdGFtcBIoCg9hdXRvUmVuZXdQZXJpb2QYBiABKAsyDy5wcm90by5EdXJhdGlvbhIPCgdzdG9yYWdlGAcgASgDEgwKBG1lbW8YCCABKAkSDwoHYmFsYW5jZRgJIAEoBBIPCgdkZWxldGVkGAogASgIEjQKEnRva2VuUmVsYXRpb25zaGlwcxgLIAMoCzIYLnByb3RvLlRva2VuUmVsYXRpb25zaGlwEhEKCWxlZGdlcl9pZBgMIAEoCRIvChVhdXRvX3JlbmV3X2FjY291bnRfaWQYDSABKAsyEC5wcm90by5BY2NvdW50SUQSKAogbWF4X2F1dG9tYXRpY190b2tlbl9hc3NvY2lhdGlvbnMYDiABKAUSHQoJYWRtaW5fa2V5GBggASgLMgoucHJvdG8uS2V5EiYKDHN0YWtpbmdfaW5mbxgZIAEoCzIQLnByb3RvLkFjY291bnRJRCJKChFDb250cmFjdE5vbmNlSW5mbxImCgtjb250cmFjdF9pZBgBIAEoCzIRLnByb3RvLkNvbnRyYWN0SUQSDQoFbm9uY2UYAiABKAMibAoTQ29udHJhY3RTdGF0ZUNoYW5nZRImCgtjb250cmFjdF9pZBgBIAEoCzIRLnByb3RvLkNvbnRyYWN0SUQSLQoPc3RvcmFnZV9jaGFuZ2VzGAIgAygLMhQucHJvdG8uU3RvcmFnZUNoYW5nZSJICg1TdG9yYWdlQ2hhbmdlEgwKBHNsb3QYASABKAwSEgoKdmFsdWVfcmVhZBgCIAEoDBIVCg12YWx1ZV93cml0dGVuGAMgASgMQiYKImNvbS5oZWRlcmFoYXNoZ3JhcGguYXBpLnByb3RvLmphdmFQAWIGcHJvdG8z", [file_basic_types, file_timestamp, file_duration, file_response_code, file_common]);

/**
 * Describes the message proto.ContractGetInfoResponse.
 * Use `create(ContractGetInfoResponseSchema)` to create a new message.
 */
export const ContractGetInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_contract_types, 0);

/**
 * Describes the message proto.ContractGetInfoResponse.ContractInfo.
 * Use `create(ContractGetInfoResponse_ContractInfoSchema)` to create a new message.
 */
export const ContractGetInfoResponse_ContractInfoSchema = /*@__PURE__*/
  messageDesc(file_contract_types, 0, 0);

/**
 * Describes the message proto.ContractNonceInfo.
 * Use `create(ContractNonceInfoSchema)` to create a new message.
 */
export const ContractNonceInfoSchema = /*@__PURE__*/
  messageDesc(file_contract_types, 1);

/**
 * Describes the message proto.ContractStateChange.
 * Use `create(ContractStateChangeSchema)` to create a new message.
 */
export const ContractStateChangeSchema = /*@__PURE__*/
  messageDesc(file_contract_types, 2);

/**
 * Describes the message proto.StorageChange.
 * Use `create(StorageChangeSchema)` to create a new message.
 */
export const StorageChangeSchema = /*@__PURE__*/
  messageDesc(file_contract_types, 3);

