//*
// Crypto account info and balance query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file crypto_info.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AccountID, Key, KeyList, StakingInfo, TokenBalance, TokenRelationship } from "./basic_types_pb.js";
import type { Duration } from "./duration_pb.js";
import type { ResponseHeader } from "./common_pb.js";
import type { Timestamp } from "./timestamp_pb.js";

/**
 * Describes the file crypto_info.proto.
 */
export declare const file_crypto_info: GenFile;

/**
 * @generated from message proto.LiveHash
 */
export declare type LiveHash = Message<"proto.LiveHash"> & {
  /**
   * @generated from field: proto.AccountID accountId = 1;
   */
  accountId?: AccountID;

  /**
   * @generated from field: bytes hash = 2;
   */
  hash: Uint8Array;

  /**
   * @generated from field: proto.KeyList keys = 3;
   */
  keys?: KeyList;

  /**
   * @generated from field: proto.Duration duration = 4;
   */
  duration?: Duration;
};

/**
 * Describes the message proto.LiveHash.
 * Use `create(LiveHashSchema)` to create a new message.
 */
export declare const LiveHashSchema: GenMessage<LiveHash>;

/**
 * @generated from message proto.CryptoGetInfoResponse
 */
export declare type CryptoGetInfoResponse = Message<"proto.CryptoGetInfoResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.CryptoGetInfoResponse.AccountInfo accountInfo = 2;
   */
  accountInfo?: CryptoGetInfoResponse_AccountInfo;
};

/**
 * Describes the message proto.CryptoGetInfoResponse.
 * Use `create(CryptoGetInfoResponseSchema)` to create a new message.
 */
export declare const CryptoGetInfoResponseSchema: GenMessage<CryptoGetInfoResponse>;

/**
 * @generated from message proto.CryptoGetInfoResponse.AccountInfo
 */
export declare type CryptoGetInfoResponse_AccountInfo = Message<"proto.CryptoGetInfoResponse.AccountInfo"> & {
  /**
   * @generated from field: proto.AccountID accountID = 1;
   */
  accountID?: AccountID;

  /**
   * @generated from field: string contractAccountID = 2;
   */
  contractAccountID: string;

  /**
   * @generated from field: bool deleted = 3;
   */
  deleted: boolean;

  /**
   * @generated from field: proto.AccountID proxyAccountID = 4 [deprecated = true];
   * @deprecated
   */
  proxyAccountID?: AccountID;

  /**
   * @generated from field: int64 proxyReceived = 6;
   */
  proxyReceived: bigint;

  /**
   * @generated from field: proto.Key key = 7;
   */
  key?: Key;

  /**
   * @generated from field: uint64 balance = 8;
   */
  balance: bigint;

  /**
   * @generated from field: uint64 generateSendRecordThreshold = 9 [deprecated = true];
   * @deprecated
   */
  generateSendRecordThreshold: bigint;

  /**
   * @generated from field: uint64 generateReceiveRecordThreshold = 10 [deprecated = true];
   * @deprecated
   */
  generateReceiveRecordThreshold: bigint;

  /**
   * @generated from field: bool receiverSigRequired = 11;
   */
  receiverSigRequired: boolean;

  /**
   * @generated from field: proto.Timestamp expirationTime = 12;
   */
  expirationTime?: Timestamp;

  /**
   * @generated from field: proto.Duration autoRenewPeriod = 13;
   */
  autoRenewPeriod?: Duration;

  /**
   * @generated from field: repeated proto.LiveHash liveHashes = 14;
   */
  liveHashes: LiveHash[];

  /**
   * @generated from field: repeated proto.TokenRelationship tokenRelationships = 15;
   */
  tokenRelationships: TokenRelationship[];

  /**
   * @generated from field: string memo = 16;
   */
  memo: string;

  /**
   * @generated from field: int64 ownedNfts = 17;
   */
  ownedNfts: bigint;

  /**
   * @generated from field: int32 max_automatic_token_associations = 18;
   */
  maxAutomaticTokenAssociations: number;

  /**
   * @generated from field: bytes alias = 19;
   */
  alias: Uint8Array;

  /**
   * @generated from field: string ledger_id = 20;
   */
  ledgerId: string;

  /**
   * @generated from field: repeated proto.TokenBalance ethereum_nonce = 21;
   */
  ethereumNonce: TokenBalance[];

  /**
   * @generated from field: proto.StakingInfo staking_info = 22;
   */
  stakingInfo?: StakingInfo;
};

/**
 * Describes the message proto.CryptoGetInfoResponse.AccountInfo.
 * Use `create(CryptoGetInfoResponse_AccountInfoSchema)` to create a new message.
 */
export declare const CryptoGetInfoResponse_AccountInfoSchema: GenMessage<CryptoGetInfoResponse_AccountInfo>;

/**
 * @generated from message proto.CryptoGetAccountBalanceResponse
 */
export declare type CryptoGetAccountBalanceResponse = Message<"proto.CryptoGetAccountBalanceResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.AccountID accountID = 2;
   */
  accountID?: AccountID;

  /**
   * @generated from field: uint64 balance = 3;
   */
  balance: bigint;

  /**
   * @generated from field: repeated proto.TokenBalance tokenBalances = 4;
   */
  tokenBalances: TokenBalance[];
};

/**
 * Describes the message proto.CryptoGetAccountBalanceResponse.
 * Use `create(CryptoGetAccountBalanceResponseSchema)` to create a new message.
 */
export declare const CryptoGetAccountBalanceResponseSchema: GenMessage<CryptoGetAccountBalanceResponse>;

