//*
// Crypto account info and balance query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file crypto_info.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_duration } from "./duration_pb.js";
import { file_response_code } from "./response_code_pb.js";
import { file_common } from "./common_pb.js";

/**
 * Describes the file crypto_info.proto.
 */
export const file_crypto_info = /*@__PURE__*/
  fileDesc("ChFjcnlwdG9faW5mby5wcm90bxIFcHJvdG8ifgoITGl2ZUhhc2gSIwoJYWNjb3VudElkGAEgASgLMhAucHJvdG8uQWNjb3VudElEEgwKBGhhc2gYAiABKAwSHAoEa2V5cxgDIAEoCzIOLnByb3RvLktleUxpc3QSIQoIZHVyYXRpb24YBCABKAsyDy5wcm90by5EdXJhdGlvbiKyBgoVQ3J5cHRvR2V0SW5mb1Jlc3BvbnNlEiUKBmhlYWRlchgBIAEoCzIVLnByb3RvLlJlc3BvbnNlSGVhZGVyEj0KC2FjY291bnRJbmZvGAIgASgLMigucHJvdG8uQ3J5cHRvR2V0SW5mb1Jlc3BvbnNlLkFjY291bnRJbmZvGrIFCgtBY2NvdW50SW5mbxIjCglhY2NvdW50SUQYASABKAsyEC5wcm90by5BY2NvdW50SUQSGQoRY29udHJhY3RBY2NvdW50SUQYAiABKAkSDwoHZGVsZXRlZBgDIAEoCBIsCg5wcm94eUFjY291bnRJRBgEIAEoCzIQLnByb3RvLkFjY291bnRJREICGAESFQoNcHJveHlSZWNlaXZlZBgGIAEoAxIXCgNrZXkYByABKAsyCi5wcm90by5LZXkSDwoHYmFsYW5jZRgIIAEoBBInChtnZW5lcmF0ZVNlbmRSZWNvcmRUaHJlc2hvbGQYCSABKARCAhgBEioKHmdlbmVyYXRlUmVjZWl2ZVJlY29yZFRocmVzaG9sZBgKIAEoBEICGAESGwoTcmVjZWl2ZXJTaWdSZXF1aXJlZBgLIAEoCBIoCg5leHBpcmF0aW9uVGltZRgMIAEoCzIQLnByb3RvLlRpbWVzdGFtcBIoCg9hdXRvUmVuZXdQZXJpb2QYDSABKAsyDy5wcm90by5EdXJhdGlvbhIjCgpsaXZlSGFzaGVzGA4gAygLMg8ucHJvdG8uTGl2ZUhhc2gSNAoSdG9rZW5SZWxhdGlvbnNoaXBzGA8gAygLMhgucHJvdG8uVG9rZW5SZWxhdGlvbnNoaXASDAoEbWVtbxgQIAEoCRIRCglvd25lZE5mdHMYESABKAMSKAogbWF4X2F1dG9tYXRpY190b2tlbl9hc3NvY2lhdGlvbnMYEiABKAUSDQoFYWxpYXMYEyABKAwSEQoJbGVkZ2VyX2lkGBQgASgJEisKDmV0aGVyZXVtX25vbmNlGBUgAygLMhMucHJvdG8uVG9rZW5CYWxhbmNlEigKDHN0YWtpbmdfaW5mbxgWIAEoCzISLnByb3RvLlN0YWtpbmdJbmZvIqoBCh9DcnlwdG9HZXRBY2NvdW50QmFsYW5jZVJlc3BvbnNlEiUKBmhlYWRlchgBIAEoCzIVLnByb3RvLlJlc3BvbnNlSGVhZGVyEiMKCWFjY291bnRJRBgCIAEoCzIQLnByb3RvLkFjY291bnRJRBIPCgdiYWxhbmNlGAMgASgEEioKDXRva2VuQmFsYW5jZXMYBCADKAsyEy5wcm90by5Ub2tlbkJhbGFuY2VCJgoiY29tLmhlZGVyYWhhc2hncmFwaC5hcGkucHJvdG8uamF2YVABYgZwcm90bzM", [file_basic_types, file_timestamp, file_duration, file_response_code, file_common]);

/**
 * Describes the message proto.LiveHash.
 * Use `create(LiveHashSchema)` to create a new message.
 */
export const LiveHashSchema = /*@__PURE__*/
  messageDesc(file_crypto_info, 0);

/**
 * Describes the message proto.CryptoGetInfoResponse.
 * Use `create(CryptoGetInfoResponseSchema)` to create a new message.
 */
export const CryptoGetInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_crypto_info, 1);

/**
 * Describes the message proto.CryptoGetInfoResponse.AccountInfo.
 * Use `create(CryptoGetInfoResponse_AccountInfoSchema)` to create a new message.
 */
export const CryptoGetInfoResponse_AccountInfoSchema = /*@__PURE__*/
  messageDesc(file_crypto_info, 1, 0);

/**
 * Describes the message proto.CryptoGetAccountBalanceResponse.
 * Use `create(CryptoGetAccountBalanceResponseSchema)` to create a new message.
 */
export const CryptoGetAccountBalanceResponseSchema = /*@__PURE__*/
  messageDesc(file_crypto_info, 2);

