//*
// # Custom Fees
// Fees defined by token creators that are charged as part of each
// transfer of that token type.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file custom_fees.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AccountID, Fraction, Key, TokenID } from "./basic_types_pb.js";

/**
 * Describes the file custom_fees.proto.
 */
export declare const file_custom_fees: GenFile;

/**
 * *
 * A descriptor for a fee based on a portion of the tokens transferred.
 *
 * This fee option describes fees as a fraction of the amount of
 * fungible/common token(s) transferred.  The fee also describes a minimum
 * and maximum amount, both of which are OPTIONAL.
 *
 * This type of fee SHALL be assessed only for fungible/common tokens.<br/>
 * This type of fee MUST NOT be defined for a non-fungible/unique
 * token type.<br/>
 * This fee SHALL be paid with the same type of tokens as those
 * transferred.<br/>
 * The fee MAY be subtracted from the transferred tokens, or MAY be assessed
 * to the sender in addition to the tokens actually transferred, based on
 * the `net_of_transfers` field.
 *
 * When a single transaction sends tokens from one sender to multiple
 * recipients, and the `net_of_transfers` flag is false, the network
 * SHALL attempt to evenly assess the total fee across all recipients
 * proportionally. This may be inexact and, particularly when there are
 * large differences between recipients, MAY result in small deviations
 * from an ideal "fair" distribution.<br/>
 * If the sender lacks sufficient tokens to pay fees, or the assessment
 * of custom fees reduces the net amount transferred to or below zero,
 * the transaction MAY fail due to insufficient funds to pay all fees.
 *
 * @generated from message proto.FractionalFee
 */
export declare type FractionalFee = Message<"proto.FractionalFee"> & {
  /**
   * *
   * A Fraction of the transferred tokens to assess as a fee.<br/>
   * This value MUST be less than or equal to one.<br/>
   * This value MUST be greater than zero.
   *
   * @generated from field: proto.Fraction fractional_amount = 1;
   */
  fractionalAmount?: Fraction;

  /**
   * *
   * A minimum fee to charge, in units of 10<sup>-decimals</sup> tokens.
   * <p>
   * This value is OPTIONAL, with a default of `0` indicating no minimum.<br/>
   * If set, this value MUST be greater than zero.<br/>
   * If set, all transfers SHALL pay at least this amount.
   *
   * @generated from field: int64 minimum_amount = 2;
   */
  minimumAmount: bigint;

  /**
   * *
   * A maximum fee to charge, in units of 10<sup>-decimals</sup> tokens.
   * <p>
   * This value is OPTIONAL, with a default of `0` indicating no maximum.<br/>
   * If set, this value MUST be greater than zero.<br/>
   * If set, any fee charged SHALL NOT exceed this value.<br/>
   * This value SHOULD be strictly greater than `minimum_amount`.
   * If this amount is less than or equal to `minimum_amount`, then
   * the fee charged SHALL always be equal to this value and
   * `fractional_amount` SHALL NOT have any effect.
   *
   * @generated from field: int64 maximum_amount = 3;
   */
  maximumAmount: bigint;

  /**
   * *
   * Flag requesting to assess the calculated fee against the sender,
   * without reducing the amount transferred.<br/>
   * #### Effects of this flag
   * <ol>
   *   <li>If this value is true
   *     <ul>
   *       <li>The receiver of a transfer SHALL receive the entire
   *           amount sent.</li>
   *       <li>The fee SHALL be charged to the sender as an additional
   *           amount, increasing the token transfer debit.</li>
   *     </ul>
   *   </li>
   *   <li>If this value is false
   *     <ul>
   *       <li>The receiver of a transfer SHALL receive the amount sent
   *           _after_ deduction of the calculated fee.</li>
   *     </ul>
   *   </li>
   * </ol>
   *
   * @generated from field: bool net_of_transfers = 4;
   */
  netOfTransfers: boolean;
};

/**
 * Describes the message proto.FractionalFee.
 * Use `create(FractionalFeeSchema)` to create a new message.
 */
export declare const FractionalFeeSchema: GenMessage<FractionalFee>;

/**
 * *
 * A fixed fee to assess for each token transfer, regardless of the
 * amount transferred.<br/>
 * This fee type describes a fixed fee for each transfer of a token type.
 *
 * The fee SHALL be charged to the `sender` for the token transfer
 * transaction.<br/>
 * This fee MAY be assessed in HBAR, the token type transferred, or any
 * other token type, as determined by the `denominating_token_id` field.
 *
 * @generated from message proto.FixedFee
 */
export declare type FixedFee = Message<"proto.FixedFee"> & {
  /**
   * *
   * The amount to assess for each transfer.
   * <p>
   * This value MUST be greater than `0`.<br/>
   * This amount is expressed in units of 10<sup>-decimals</sup> tokens.
   *
   * @generated from field: int64 amount = 1;
   */
  amount: bigint;

  /**
   * *
   * The token type used to pay the assessed fee.
   * <p>
   * If this is unset, the fee SHALL be assessed in HBAR.<br/>
   * If this is set, the fee SHALL be assessed in the token identified.
   * This MAY be any token type. Custom fees assessed in other token types
   * are more likely to fail, however, and it is RECOMMENDED that token
   * creators denominate custom fees in the transferred token, HBAR, or
   * well documented and closely related token types.<br/>
   * If this value is set to `0.0.0` in the `tokenCreate` transaction, it
   * SHALL be replaced with the `TokenID` of the newly created token.
   *
   * @generated from field: proto.TokenID denominating_token_id = 2;
   */
  denominatingTokenId?: TokenID;
};

/**
 * Describes the message proto.FixedFee.
 * Use `create(FixedFeeSchema)` to create a new message.
 */
export declare const FixedFeeSchema: GenMessage<FixedFee>;

/**
 * *
 * A fee to assess during a CryptoTransfer that changes ownership of a
 * non-fungible/unique (NFT) token.<br/>
 * This message defines the fraction of the fungible value exchanged for an
 * NFT that the ledger should collect as a royalty.
 * "Fungible value" includes both HBAR (ℏ) and units of fungible HTS tokens.
 * When the NFT sender does not receive any fungible value, the ledger will
 * assess the fallback fee, if present, to the new NFT owner. Royalty fees
 * can only be added to non-fungible/unique tokens.
 *
 * #### Important Note
 * > Users should be aware that native royalty fees are _strictly_ a
 * > convenience feature, SHALL NOT be guaranteed, and the network SHALL NOT
 * > enforce _inescapable_ royalties on the exchange of a unique NFT.<br/>
 * > For _one_ example, if the counterparties agree to split their value
 * > transfer and NFT exchange into separate transactions, the network cannot
 * > possibly determine the value exchanged. Even trustless transactions,
 * > using a smart contract or other form of escrow, can arrange such split
 * > transactions as a single _logical_ transfer.
 *
 * Counterparties that wish to _respect_ creator royalties MUST follow the
 * pattern the network recognizes.
 * <div style="margin-left: 2em; margin-top: -0.8em">
 * A single transaction MUST contain all three elements, transfer of the NFT,
 * debit of fungible value from the receiver, and credit of fungible value to
 * the sender, in order for the network to accurately assess royalty fees.
 * </div>
 * <div style="margin-left: 1em; margin-top: -0.8em">
 * Two examples are presented here.
 * <div style="margin-left: 1em">
 * The NFT sender and receiver MUST both sign a single `cryptoTransfer` that
 * transfers the NFT from sender to receiver, debits the fungible value from
 * the receiver, and credits the sender with the fungible value the receiver
 * is exchanging for the NFT.<br/>
 * A marketplace using an approved spender account for an escrow transaction
 * MUST credit the account selling the NFT in the same `cryptoTransfer`
 * transaction that transfers the NFT to, and deducts fungible value from,
 * the buying account.
 * </div></div>
 * This type of fee MAY NOT produce accurate results if multiple transfers
 * are executed in a single transaction. It is RECOMMENDED that each
 * NFT subject to royalty fees be transferred separately and without
 * unrelated fungible token transfers.
 *
 * The network SHALL NOT consider third-party transfers, including
 * "approved spender" accounts, in collecting royalty fees. An honest
 * broker MUST ensure that transfer of an NFT and payment delivered to
 * the sender are present in the same transaction.
 * There is an
 * [open suggestion](https://github.com/hashgraph/hedera-improvement-proposal/discussions/578)
 * that proposes to broaden the scope of transfers from which the network
 * automatically collects royalties to cover related third parties. If this
 * interests or concerns you, please add your voice to that discussion.
 *
 * @generated from message proto.RoyaltyFee
 */
export declare type RoyaltyFee = Message<"proto.RoyaltyFee"> & {
  /**
   * *
   * The fraction of fungible value exchanged for an NFT to collect
   * as royalty.
   * <p>
   * This SHALL be applied once to the total fungible value transferred
   * for the transaction.<br/>
   * There SHALL NOT be any adjustment based on multiple transfers
   * involving the NFT sender as part of a single transaction.
   *
   * @generated from field: proto.Fraction exchange_value_fraction = 1;
   */
  exchangeValueFraction?: Fraction;

  /**
   * *
   * A fixed fee to assess if no fungible value is known to be traded
   * for the NFT.
   * <p>
   * If an NFT is transferred without a corresponding transfer of
   * _fungible_ value returned in the same transaction, the network
   * SHALL charge this fee as a fallback.<br/>
   * Fallback fees MAY have unexpected effects when interacting with
   * escrow, market transfers, and smart contracts.
   * It is RECOMMENDED that developers carefully consider possible
   * effects from fallback fees when designing systems that facilitate
   * the transfer of NFTs.
   *
   * @generated from field: proto.FixedFee fallback_fee = 2;
   */
  fallbackFee?: FixedFee;
};

/**
 * Describes the message proto.RoyaltyFee.
 * Use `create(RoyaltyFeeSchema)` to create a new message.
 */
export declare const RoyaltyFeeSchema: GenMessage<RoyaltyFee>;

/**
 * *
 * A transfer fee to assess during a CryptoTransfer.<br/>
 * This fee applies to transactions that transfer units of the token to
 * which the fee is attached. A custom fee may be either fixed or fractional,
 * and must specify a fee collector account to receive the assessed fees.
 *
 * Custom fees MUST be greater than zero (0).
 *
 * @generated from message proto.CustomFee
 */
export declare type CustomFee = Message<"proto.CustomFee"> & {
  /**
   * @generated from oneof proto.CustomFee.fee
   */
  fee: {
    /**
     * *
     * A fixed fee to be charged to the `sender` for every token transfer.
     * <p>
     * This type of fee MAY be defined for any token type.<br/>
     * This type of fee MAY be more consistent and reliable than
     * other types.
     *
     * @generated from field: proto.FixedFee fixed_fee = 1;
     */
    value: FixedFee;
    case: "fixedFee";
  } | {
    /**
     * *
     * A fee defined as a fraction of the tokens transferred.
     * <p>
     * This type of fee MUST NOT be defined for a non-fungible/unique
     * token type.<br/>
     * This fee MAY be charged to either sender, as an increase to the
     * amount sent, or receiver, as a reduction to the amount received.
     *
     * @generated from field: proto.FractionalFee fractional_fee = 2;
     */
    value: FractionalFee;
    case: "fractionalFee";
  } | {
    /**
     * *
     * A fee charged as royalty for any transfer of a
     * non-fungible/unique token.
     * <p>
     * This type of fee MUST NOT be defined for a
     * fungible/common token type.
     *
     * @generated from field: proto.RoyaltyFee royalty_fee = 4;
     */
    value: RoyaltyFee;
    case: "royaltyFee";
  } | { case: undefined; value?: undefined };

  /**
   * *
   * The account to receive the custom fee.
   *
   * @generated from field: proto.AccountID fee_collector_account_id = 3;
   */
  feeCollectorAccountId?: AccountID;

  /**
   * *
   * Flag indicating to exempt all custom fee collector accounts for this
   * token type from paying this custom fee when sending tokens.
   * <p>
   * The treasury account for a token, and the account identified by the
   * `fee_collector_account_id` field of this `CustomFee` are always exempt
   * from this custom fee to avoid redundant and unnecessary transfers.
   * If this value is `true` then the account(s) identified in
   * `fee_collector_account_id` for _all_ custom fee definitions for this
   * token type SHALL also be exempt from this custom fee.
   * This behavior is specified in HIP-573.
   *
   * @generated from field: bool all_collectors_are_exempt = 5;
   */
  allCollectorsAreExempt: boolean;
};

/**
 * Describes the message proto.CustomFee.
 * Use `create(CustomFeeSchema)` to create a new message.
 */
export declare const CustomFeeSchema: GenMessage<CustomFee>;

/**
 * *
 * Description of a transfer added to a `cryptoTransfer` transaction that
 * satisfies custom fee requirements.
 *
 * It is important to note that this is not the actual transfer. The transfer
 * of value SHALL be merged into the original transaction to minimize the
 * number of actual transfers. This descriptor presents the fee assessed
 * separately in the record stream so that the details of the fee assessed
 * are not hidden in this process.
 *
 * @generated from message proto.AssessedCustomFee
 */
export declare type AssessedCustomFee = Message<"proto.AssessedCustomFee"> & {
  /**
   * *
   * An amount of tokens assessed for this custom fee.
   * <p>
   * This shall be expressed in units of 10<sup>-decimals</sup> tokens.
   *
   * @generated from field: int64 amount = 1;
   */
  amount: bigint;

  /**
   * *
   * The token transferred to satisfy this fee.
   * <p>
   * If the token transferred is HBAR, this field SHALL NOT be set.
   *
   * @generated from field: proto.TokenID token_id = 2;
   */
  tokenId?: TokenID;

  /**
   * *
   * An account that received the fee assessed.
   * <p>
   * This SHALL NOT be the sender or receiver of the original
   * cryptoTransfer transaction.
   *
   * @generated from field: proto.AccountID fee_collector_account_id = 3;
   */
  feeCollectorAccountId?: AccountID;

  /**
   * *
   * An account that provided the tokens assessed as a fee.
   * <p>
   * This SHALL be the account that _would have_ had a higher balance
   * absent the fee. In most cases this SHALL be the `sender`, but
   * some _fractional_ fees reduce the amount transferred, and in those
   * cases the `receiver` SHALL be the effective payer for the fee.<br/>
   * There are currently no situations where a third party pays a custom
   * fee. This MAY change in a future release.
   *
   * @generated from field: repeated proto.AccountID effective_payer_account_id = 4;
   */
  effectivePayerAccountId: AccountID[];
};

/**
 * Describes the message proto.AssessedCustomFee.
 * Use `create(AssessedCustomFeeSchema)` to create a new message.
 */
export declare const AssessedCustomFeeSchema: GenMessage<AssessedCustomFee>;

/**
 * *
 * A custom fee definition for a consensus topic.
 * <p>
 * This fee definition is specific to an Hedera Consensus Service (HCS) topic
 * and SHOULD NOT be used in any other context.<br/>
 * All fields for this message are REQUIRED.<br/>
 * Only "fixed" fee definitions are supported because there is no basis for
 * a fractional fee on a consensus submit transaction.
 *
 * @generated from message proto.FixedCustomFee
 */
export declare type FixedCustomFee = Message<"proto.FixedCustomFee"> & {
  /**
   * *
   * A fixed custom fee.
   * <p>
   * The amount of HBAR or other token described by this `FixedFee` SHALL
   * be charged to the transction payer for each message submitted to a
   * topic that assigns this consensus custom fee.
   *
   * @generated from field: proto.FixedFee fixed_fee = 1;
   */
  fixedFee?: FixedFee;

  /**
   * *
   * A collection account identifier.
   * <p>
   * All amounts collected for this consensus custom fee SHALL be transferred
   * to the account identified by this field.
   *
   * @generated from field: proto.AccountID fee_collector_account_id = 2;
   */
  feeCollectorAccountId?: AccountID;
};

/**
 * Describes the message proto.FixedCustomFee.
 * Use `create(FixedCustomFeeSchema)` to create a new message.
 */
export declare const FixedCustomFeeSchema: GenMessage<FixedCustomFee>;

/**
 * *
 * A wrapper around a consensus custom fee list.<br/>
 * This wrapper exists to enable an update transaction to differentiate between
 *  a field that is not set and an empty list of custom fees.
 * <p>
 * An _unset_ field of this type SHALL NOT modify existing values.<br/>
 * A _set_ field of this type with an empty `fees` list SHALL remove any
 *  existing values.
 *
 * @generated from message proto.FixedCustomFeeList
 */
export declare type FixedCustomFeeList = Message<"proto.FixedCustomFeeList"> & {
  /**
   * *
   * A set of custom fee definitions.<br/>
   * These are fees to be assessed for each submit to a topic.
   *
   * @generated from field: repeated proto.FixedCustomFee fees = 1;
   */
  fees: FixedCustomFee[];
};

/**
 * Describes the message proto.FixedCustomFeeList.
 * Use `create(FixedCustomFeeListSchema)` to create a new message.
 */
export declare const FixedCustomFeeListSchema: GenMessage<FixedCustomFeeList>;

/**
 * *
 * A wrapper for fee exempt key list.<br/>
 * This wrapper exists to enable an update transaction to differentiate between
 * a field that is not set and an empty list of keys.
 * <p>
 * An _unset_ field of this type SHALL NOT modify existing values.<br/>
 * A _set_ field of this type with an empty `keys` list SHALL remove any
 * existing values.
 *
 * @generated from message proto.FeeExemptKeyList
 */
export declare type FeeExemptKeyList = Message<"proto.FeeExemptKeyList"> & {
  /**
   * *
   * A set of keys.<br/>
   * The keys in this list are permitted to submit messages to the
   * topic without paying the topic's custom fees.
   * <p>
   * If a submit transaction is signed by _any_ key included in this set,
   * custom fees SHALL NOT be charged for that transaction.
   *
   * @generated from field: repeated proto.Key keys = 1;
   */
  keys: Key[];
};

/**
 * Describes the message proto.FeeExemptKeyList.
 * Use `create(FeeExemptKeyListSchema)` to create a new message.
 */
export declare const FeeExemptKeyListSchema: GenMessage<FeeExemptKeyList>;

/**
 * *
 * A maximum custom fee that the user is willing to pay.
 * <p>
 * This message is used to specify the maximum custom fee that given user is
 * willing to pay.
 *
 * @generated from message proto.CustomFeeLimit
 */
export declare type CustomFeeLimit = Message<"proto.CustomFeeLimit"> & {
  /**
   * *
   * A payer account identifier.
   *
   * @generated from field: proto.AccountID account_id = 1;
   */
  accountId?: AccountID;

  /**
   * *
   * The maximum fees that the user is willing to pay for the message.
   *
   * @generated from field: repeated proto.FixedFee fees = 2;
   */
  fees: FixedFee[];
};

/**
 * Describes the message proto.CustomFeeLimit.
 * Use `create(CustomFeeLimitSchema)` to create a new message.
 */
export declare const CustomFeeLimitSchema: GenMessage<CustomFeeLimit>;

