//*
// # Custom Fees
// Fees defined by token creators that are charged as part of each
// transfer of that token type.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file custom_fees.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";

/**
 * Describes the file custom_fees.proto.
 */
export const file_custom_fees = /*@__PURE__*/
  fileDesc("ChFjdXN0b21fZmVlcy5wcm90bxIFcHJvdG8ihQEKDUZyYWN0aW9uYWxGZWUSKgoRZnJhY3Rpb25hbF9hbW91bnQYASABKAsyDy5wcm90by5GcmFjdGlvbhIWCg5taW5pbXVtX2Ftb3VudBgCIAEoAxIWCg5tYXhpbXVtX2Ftb3VudBgDIAEoAxIYChBuZXRfb2ZfdHJhbnNmZXJzGAQgASgIIkkKCEZpeGVkRmVlEg4KBmFtb3VudBgBIAEoAxItChVkZW5vbWluYXRpbmdfdG9rZW5faWQYAiABKAsyDi5wcm90by5Ub2tlbklEImUKClJveWFsdHlGZWUSMAoXZXhjaGFuZ2VfdmFsdWVfZnJhY3Rpb24YASABKAsyDy5wcm90by5GcmFjdGlvbhIlCgxmYWxsYmFja19mZWUYAiABKAsyDy5wcm90by5GaXhlZEZlZSLpAQoJQ3VzdG9tRmVlEiQKCWZpeGVkX2ZlZRgBIAEoCzIPLnByb3RvLkZpeGVkRmVlSAASLgoOZnJhY3Rpb25hbF9mZWUYAiABKAsyFC5wcm90by5GcmFjdGlvbmFsRmVlSAASKAoLcm95YWx0eV9mZWUYBCABKAsyES5wcm90by5Sb3lhbHR5RmVlSAASMgoYZmVlX2NvbGxlY3Rvcl9hY2NvdW50X2lkGAMgASgLMhAucHJvdG8uQWNjb3VudElEEiEKGWFsbF9jb2xsZWN0b3JzX2FyZV9leGVtcHQYBSABKAhCBQoDZmVlIq8BChFBc3Nlc3NlZEN1c3RvbUZlZRIOCgZhbW91bnQYASABKAMSIAoIdG9rZW5faWQYAiABKAsyDi5wcm90by5Ub2tlbklEEjIKGGZlZV9jb2xsZWN0b3JfYWNjb3VudF9pZBgDIAEoCzIQLnByb3RvLkFjY291bnRJRBI0ChplZmZlY3RpdmVfcGF5ZXJfYWNjb3VudF9pZBgEIAMoCzIQLnByb3RvLkFjY291bnRJRCJoCg5GaXhlZEN1c3RvbUZlZRIiCglmaXhlZF9mZWUYASABKAsyDy5wcm90by5GaXhlZEZlZRIyChhmZWVfY29sbGVjdG9yX2FjY291bnRfaWQYAiABKAsyEC5wcm90by5BY2NvdW50SUQiOQoSRml4ZWRDdXN0b21GZWVMaXN0EiMKBGZlZXMYASADKAsyFS5wcm90by5GaXhlZEN1c3RvbUZlZSIsChBGZWVFeGVtcHRLZXlMaXN0EhgKBGtleXMYASADKAsyCi5wcm90by5LZXkiVQoOQ3VzdG9tRmVlTGltaXQSJAoKYWNjb3VudF9pZBgBIAEoCzIQLnByb3RvLkFjY291bnRJRBIdCgRmZWVzGAIgAygLMg8ucHJvdG8uRml4ZWRGZWVCJgoiY29tLmhlZGVyYWhhc2hncmFwaC5hcGkucHJvdG8uamF2YVABYgZwcm90bzM", [file_basic_types]);

/**
 * Describes the message proto.FractionalFee.
 * Use `create(FractionalFeeSchema)` to create a new message.
 */
export const FractionalFeeSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 0);

/**
 * Describes the message proto.FixedFee.
 * Use `create(FixedFeeSchema)` to create a new message.
 */
export const FixedFeeSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 1);

/**
 * Describes the message proto.RoyaltyFee.
 * Use `create(RoyaltyFeeSchema)` to create a new message.
 */
export const RoyaltyFeeSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 2);

/**
 * Describes the message proto.CustomFee.
 * Use `create(CustomFeeSchema)` to create a new message.
 */
export const CustomFeeSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 3);

/**
 * Describes the message proto.AssessedCustomFee.
 * Use `create(AssessedCustomFeeSchema)` to create a new message.
 */
export const AssessedCustomFeeSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 4);

/**
 * Describes the message proto.FixedCustomFee.
 * Use `create(FixedCustomFeeSchema)` to create a new message.
 */
export const FixedCustomFeeSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 5);

/**
 * Describes the message proto.FixedCustomFeeList.
 * Use `create(FixedCustomFeeListSchema)` to create a new message.
 */
export const FixedCustomFeeListSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 6);

/**
 * Describes the message proto.FeeExemptKeyList.
 * Use `create(FeeExemptKeyListSchema)` to create a new message.
 */
export const FeeExemptKeyListSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 7);

/**
 * Describes the message proto.CustomFeeLimit.
 * Use `create(CustomFeeLimitSchema)` to create a new message.
 */
export const CustomFeeLimitSchema = /*@__PURE__*/
  messageDesc(file_custom_fees, 8);

