//*
// # Duration
// A duration, in seconds.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file duration.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file duration.proto.
 */
export const file_duration = /*@__PURE__*/
  fileDesc("Cg5kdXJhdGlvbi5wcm90bxIFcHJvdG8iGwoIRHVyYXRpb24SDwoHc2Vjb25kcxgBIAEoA0ImCiJjb20uaGVkZXJhaGFzaGdyYXBoLmFwaS5wcm90by5qYXZhUAFiBnByb3RvMw");

/**
 * Describes the message proto.Duration.
 * Use `create(DurationSchema)` to create a new message.
 */
export const DurationSchema = /*@__PURE__*/
  messageDesc(file_duration, 0);

