//*
// # Duration
// A duration, in seconds.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file duration.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file duration.proto.
 */
export declare const file_duration: GenFile;

/**
 * *
 * A length of time in seconds.
 *
 * It is RECOMMENDED that this message be used whenever an amount of time,
 * rather than a specific point in time, is needed.
 *
 * @generated from message proto.Duration
 */
export declare type Duration = Message<"proto.Duration"> & {
  /**
   * *
   * The number of seconds for this duration.
   *
   * @generated from field: int64 seconds = 1;
   */
  seconds: bigint;
};

/**
 * Describes the message proto.Duration.
 * Use `create(DurationSchema)` to create a new message.
 */
export declare const DurationSchema: GenMessage<Duration>;

