//*
// Fee and exchange rate types.
// ExchangeRate/ExchangeRateSet are in receipt_record.proto.
// FeeSchedule/FeeData/FeeComponents/TransactionFeeSchedule are in basic_types.proto.
// This file re-exports via the wrapper for SDK compatibility.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file fee_types.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file fee_types.proto.
 */
export declare const file_fee_types: GenFile;

