//*
// Fee and exchange rate types.
// ExchangeRate/ExchangeRateSet are in receipt_record.proto.
// FeeSchedule/FeeData/FeeComponents/TransactionFeeSchedule are in basic_types.proto.
// This file re-exports via the wrapper for SDK compatibility.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file fee_types.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_receipt_record } from "./receipt_record_pb.js";

/**
 * Describes the file fee_types.proto.
 */
export const file_fee_types = /*@__PURE__*/
  fileDesc("Cg9mZWVfdHlwZXMucHJvdG8SBXByb3RvQiYKImNvbS5oZWRlcmFoYXNoZ3JhcGguYXBpLnByb3RvLmphdmFQAWIGcHJvdG8z", [file_basic_types, file_receipt_record]);

