//*
// File info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file file_info.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_response_code } from "./response_code_pb.js";
import { file_common } from "./common_pb.js";

/**
 * Describes the file file_info.proto.
 */
export const file_file_info = /*@__PURE__*/
  fileDesc("Cg9maWxlX2luZm8ucHJvdG8SBXByb3RvIqcCChNGaWxlR2V0SW5mb1Jlc3BvbnNlEiUKBmhlYWRlchgBIAEoCzIVLnByb3RvLlJlc3BvbnNlSGVhZGVyEjUKCGZpbGVJbmZvGAIgASgLMiMucHJvdG8uRmlsZUdldEluZm9SZXNwb25zZS5GaWxlSW5mbxqxAQoIRmlsZUluZm8SHQoGZmlsZUlEGAEgASgLMg0ucHJvdG8uRmlsZUlEEgwKBHNpemUYAiABKAMSKAoOZXhwaXJhdGlvblRpbWUYAyABKAsyEC5wcm90by5UaW1lc3RhbXASDwoHZGVsZXRlZBgEIAEoCBIcCgRrZXlzGAUgASgLMg4ucHJvdG8uS2V5TGlzdBIMCgRtZW1vGAYgASgJEhEKCWxlZGdlcl9pZBgHIAEoCSLEAQoXRmlsZUdldENvbnRlbnRzUmVzcG9uc2USJQoGaGVhZGVyGAEgASgLMhUucHJvdG8uUmVzcG9uc2VIZWFkZXISQQoMZmlsZUNvbnRlbnRzGAIgASgLMisucHJvdG8uRmlsZUdldENvbnRlbnRzUmVzcG9uc2UuRmlsZUNvbnRlbnRzGj8KDEZpbGVDb250ZW50cxIdCgZmaWxlSUQYASABKAsyDS5wcm90by5GaWxlSUQSEAoIY29udGVudHMYAiABKAxCJgoiY29tLmhlZGVyYWhhc2hncmFwaC5hcGkucHJvdG8uamF2YVABYgZwcm90bzM", [file_basic_types, file_timestamp, file_response_code, file_common]);

/**
 * Describes the message proto.FileGetInfoResponse.
 * Use `create(FileGetInfoResponseSchema)` to create a new message.
 */
export const FileGetInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_file_info, 0);

/**
 * Describes the message proto.FileGetInfoResponse.FileInfo.
 * Use `create(FileGetInfoResponse_FileInfoSchema)` to create a new message.
 */
export const FileGetInfoResponse_FileInfoSchema = /*@__PURE__*/
  messageDesc(file_file_info, 0, 0);

/**
 * Describes the message proto.FileGetContentsResponse.
 * Use `create(FileGetContentsResponseSchema)` to create a new message.
 */
export const FileGetContentsResponseSchema = /*@__PURE__*/
  messageDesc(file_file_info, 1);

/**
 * Describes the message proto.FileGetContentsResponse.FileContents.
 * Use `create(FileGetContentsResponse_FileContentsSchema)` to create a new message.
 */
export const FileGetContentsResponse_FileContentsSchema = /*@__PURE__*/
  messageDesc(file_file_info, 1, 0);

