//*
// File info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file file_info.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResponseHeader } from "./common_pb.js";
import type { FileID, KeyList } from "./basic_types_pb.js";
import type { Timestamp } from "./timestamp_pb.js";

/**
 * Describes the file file_info.proto.
 */
export declare const file_file_info: GenFile;

/**
 * @generated from message proto.FileGetInfoResponse
 */
export declare type FileGetInfoResponse = Message<"proto.FileGetInfoResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.FileGetInfoResponse.FileInfo fileInfo = 2;
   */
  fileInfo?: FileGetInfoResponse_FileInfo;
};

/**
 * Describes the message proto.FileGetInfoResponse.
 * Use `create(FileGetInfoResponseSchema)` to create a new message.
 */
export declare const FileGetInfoResponseSchema: GenMessage<FileGetInfoResponse>;

/**
 * @generated from message proto.FileGetInfoResponse.FileInfo
 */
export declare type FileGetInfoResponse_FileInfo = Message<"proto.FileGetInfoResponse.FileInfo"> & {
  /**
   * @generated from field: proto.FileID fileID = 1;
   */
  fileID?: FileID;

  /**
   * @generated from field: int64 size = 2;
   */
  size: bigint;

  /**
   * @generated from field: proto.Timestamp expirationTime = 3;
   */
  expirationTime?: Timestamp;

  /**
   * @generated from field: bool deleted = 4;
   */
  deleted: boolean;

  /**
   * @generated from field: proto.KeyList keys = 5;
   */
  keys?: KeyList;

  /**
   * @generated from field: string memo = 6;
   */
  memo: string;

  /**
   * @generated from field: string ledger_id = 7;
   */
  ledgerId: string;
};

/**
 * Describes the message proto.FileGetInfoResponse.FileInfo.
 * Use `create(FileGetInfoResponse_FileInfoSchema)` to create a new message.
 */
export declare const FileGetInfoResponse_FileInfoSchema: GenMessage<FileGetInfoResponse_FileInfo>;

/**
 * @generated from message proto.FileGetContentsResponse
 */
export declare type FileGetContentsResponse = Message<"proto.FileGetContentsResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.FileGetContentsResponse.FileContents fileContents = 2;
   */
  fileContents?: FileGetContentsResponse_FileContents;
};

/**
 * Describes the message proto.FileGetContentsResponse.
 * Use `create(FileGetContentsResponseSchema)` to create a new message.
 */
export declare const FileGetContentsResponseSchema: GenMessage<FileGetContentsResponse>;

/**
 * @generated from message proto.FileGetContentsResponse.FileContents
 */
export declare type FileGetContentsResponse_FileContents = Message<"proto.FileGetContentsResponse.FileContents"> & {
  /**
   * @generated from field: proto.FileID fileID = 1;
   */
  fileID?: FileID;

  /**
   * @generated from field: bytes contents = 2;
   */
  contents: Uint8Array;
};

/**
 * Describes the message proto.FileGetContentsResponse.FileContents.
 * Use `create(FileGetContentsResponse_FileContentsSchema)` to create a new message.
 */
export declare const FileGetContentsResponse_FileContentsSchema: GenMessage<FileGetContentsResponse_FileContents>;

