//*
// Miscellaneous types not covered by other proto files.
// Most types come from basic_types.proto; this file adds extras.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file misc_types.proto (package proto, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";

/**
 * Describes the file misc_types.proto.
 */
export const file_misc_types = /*@__PURE__*/
  fileDesc("ChBtaXNjX3R5cGVzLnByb3RvEgVwcm90byJACgZIb29rSWQSEQoJc2hhcmRfbnVtGAEgASgDEhEKCXJlYWxtX251bRgCIAEoAxIQCghob29rX251bRgDIAEoAyJICgxIb29rRW50aXR5SWQSEQoJc2hhcmRfbnVtGAEgASgDEhEKCXJlYWxtX251bRgCIAEoAxISCgplbnRpdHlfbnVtGAMgASgDIo8BCghIb29rQ2FsbBIeCgdob29rX2lkGAEgASgLMg0ucHJvdG8uSG9va0lkEiMKBmNhbGxlchgCIAEoCzITLnByb3RvLkhvb2tFbnRpdHlJZBIjCgZ0YXJnZXQYAyABKAsyEy5wcm90by5Ib29rRW50aXR5SWQSDAoEZGF0YRgEIAEoDBILCgNnYXMYBSABKAMieAoLRXZtSG9va0NhbGwSHgoHaG9va19pZBgBIAEoCzINLnByb3RvLkhvb2tJZBIWCg5jYWxsZXJfYWRkcmVzcxgCIAEoDBIWCg50YXJnZXRfYWRkcmVzcxgDIAEoDBIMCgRkYXRhGAQgASgMEgsKA2dhcxgFIAEoAyqIAQoKRnJlZXplVHlwZRIXChNVTktOT1dOX0ZSRUVaRV9UWVBFEAASDwoLRlJFRVpFX09OTFkQARITCg9QUkVQQVJFX1VQR1JBREUQAhISCg5GUkVFWkVfVVBHUkFERRADEhAKDEZSRUVaRV9BQk9SVBAEEhUKEVRFTEVNRVRSWV9VUEdSQURFEAVCJgoiY29tLmhlZGVyYWhhc2hncmFwaC5hcGkucHJvdG8uamF2YVABYgZwcm90bzM", [file_basic_types]);

/**
 * Describes the message proto.HookId.
 * Use `create(HookIdSchema)` to create a new message.
 */
export const HookIdSchema = /*@__PURE__*/
  messageDesc(file_misc_types, 0);

/**
 * Describes the message proto.HookEntityId.
 * Use `create(HookEntityIdSchema)` to create a new message.
 */
export const HookEntityIdSchema = /*@__PURE__*/
  messageDesc(file_misc_types, 1);

/**
 * Describes the message proto.HookCall.
 * Use `create(HookCallSchema)` to create a new message.
 */
export const HookCallSchema = /*@__PURE__*/
  messageDesc(file_misc_types, 2);

/**
 * Describes the message proto.EvmHookCall.
 * Use `create(EvmHookCallSchema)` to create a new message.
 */
export const EvmHookCallSchema = /*@__PURE__*/
  messageDesc(file_misc_types, 3);

/**
 * Describes the enum proto.FreezeType.
 */
export const FreezeTypeSchema = /*@__PURE__*/
  enumDesc(file_misc_types, 0);

/**
 * @generated from enum proto.FreezeType
 */
export const FreezeType = /*@__PURE__*/
  tsEnum(FreezeTypeSchema);

