//*
// Miscellaneous types not covered by other proto files.
// Most types come from basic_types.proto; this file adds extras.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file misc_types.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file misc_types.proto.
 */
export declare const file_misc_types: GenFile;

/**
 * @generated from message proto.HookId
 */
export declare type HookId = Message<"proto.HookId"> & {
  /**
   * @generated from field: int64 shard_num = 1;
   */
  shardNum: bigint;

  /**
   * @generated from field: int64 realm_num = 2;
   */
  realmNum: bigint;

  /**
   * @generated from field: int64 hook_num = 3;
   */
  hookNum: bigint;
};

/**
 * Describes the message proto.HookId.
 * Use `create(HookIdSchema)` to create a new message.
 */
export declare const HookIdSchema: GenMessage<HookId>;

/**
 * @generated from message proto.HookEntityId
 */
export declare type HookEntityId = Message<"proto.HookEntityId"> & {
  /**
   * @generated from field: int64 shard_num = 1;
   */
  shardNum: bigint;

  /**
   * @generated from field: int64 realm_num = 2;
   */
  realmNum: bigint;

  /**
   * @generated from field: int64 entity_num = 3;
   */
  entityNum: bigint;
};

/**
 * Describes the message proto.HookEntityId.
 * Use `create(HookEntityIdSchema)` to create a new message.
 */
export declare const HookEntityIdSchema: GenMessage<HookEntityId>;

/**
 * @generated from message proto.HookCall
 */
export declare type HookCall = Message<"proto.HookCall"> & {
  /**
   * @generated from field: proto.HookId hook_id = 1;
   */
  hookId?: HookId;

  /**
   * @generated from field: proto.HookEntityId caller = 2;
   */
  caller?: HookEntityId;

  /**
   * @generated from field: proto.HookEntityId target = 3;
   */
  target?: HookEntityId;

  /**
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * @generated from field: int64 gas = 5;
   */
  gas: bigint;
};

/**
 * Describes the message proto.HookCall.
 * Use `create(HookCallSchema)` to create a new message.
 */
export declare const HookCallSchema: GenMessage<HookCall>;

/**
 * @generated from message proto.EvmHookCall
 */
export declare type EvmHookCall = Message<"proto.EvmHookCall"> & {
  /**
   * @generated from field: proto.HookId hook_id = 1;
   */
  hookId?: HookId;

  /**
   * @generated from field: bytes caller_address = 2;
   */
  callerAddress: Uint8Array;

  /**
   * @generated from field: bytes target_address = 3;
   */
  targetAddress: Uint8Array;

  /**
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * @generated from field: int64 gas = 5;
   */
  gas: bigint;
};

/**
 * Describes the message proto.EvmHookCall.
 * Use `create(EvmHookCallSchema)` to create a new message.
 */
export declare const EvmHookCallSchema: GenMessage<EvmHookCall>;

/**
 * @generated from enum proto.FreezeType
 */
export enum FreezeType {
  /**
   * @generated from enum value: UNKNOWN_FREEZE_TYPE = 0;
   */
  UNKNOWN_FREEZE_TYPE = 0,

  /**
   * @generated from enum value: FREEZE_ONLY = 1;
   */
  FREEZE_ONLY = 1,

  /**
   * @generated from enum value: PREPARE_UPGRADE = 2;
   */
  PREPARE_UPGRADE = 2,

  /**
   * @generated from enum value: FREEZE_UPGRADE = 3;
   */
  FREEZE_UPGRADE = 3,

  /**
   * @generated from enum value: FREEZE_ABORT = 4;
   */
  FREEZE_ABORT = 4,

  /**
   * @generated from enum value: TELEMETRY_UPGRADE = 5;
   */
  TELEMETRY_UPGRADE = 5,
}

/**
 * Describes the enum proto.FreezeType.
 */
export declare const FreezeTypeSchema: GenEnum<FreezeType>;

