//*
// Network info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file network_info.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResponseHeader } from "./common_pb.js";
import type { SemanticVersion } from "./basic_types_pb.js";

/**
 * Describes the file network_info.proto.
 */
export declare const file_network_info: GenFile;

/**
 * @generated from message proto.NetworkGetVersionInfoResponse
 */
export declare type NetworkGetVersionInfoResponse = Message<"proto.NetworkGetVersionInfoResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.SemanticVersion hapiProtoVersion = 2;
   */
  hapiProtoVersion?: SemanticVersion;

  /**
   * @generated from field: proto.SemanticVersion hederaServicesVersion = 3;
   */
  hederaServicesVersion?: SemanticVersion;
};

/**
 * Describes the message proto.NetworkGetVersionInfoResponse.
 * Use `create(NetworkGetVersionInfoResponseSchema)` to create a new message.
 */
export declare const NetworkGetVersionInfoResponseSchema: GenMessage<NetworkGetVersionInfoResponse>;

