//*
// Network info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file network_info.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_response_code } from "./response_code_pb.js";
import { file_common } from "./common_pb.js";

/**
 * Describes the file network_info.proto.
 */
export const file_network_info = /*@__PURE__*/
  fileDesc("ChJuZXR3b3JrX2luZm8ucHJvdG8SBXByb3RvIq8BCh1OZXR3b3JrR2V0VmVyc2lvbkluZm9SZXNwb25zZRIlCgZoZWFkZXIYASABKAsyFS5wcm90by5SZXNwb25zZUhlYWRlchIwChBoYXBpUHJvdG9WZXJzaW9uGAIgASgLMhYucHJvdG8uU2VtYW50aWNWZXJzaW9uEjUKFWhlZGVyYVNlcnZpY2VzVmVyc2lvbhgDIAEoCzIWLnByb3RvLlNlbWFudGljVmVyc2lvbkImCiJjb20uaGVkZXJhaGFzaGdyYXBoLmFwaS5wcm90by5qYXZhUAFiBnByb3RvMw", [file_basic_types, file_timestamp, file_response_code, file_common]);

/**
 * Describes the message proto.NetworkGetVersionInfoResponse.
 * Use `create(NetworkGetVersionInfoResponseSchema)` to create a new message.
 */
export const NetworkGetVersionInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_network_info, 0);

