//*
// Transaction receipt and record types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file receipt_record.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResponseCodeEnum } from "./response_code_pb.js";
import type { AccountID, ContractID, FileID, ScheduleID, TokenAssociation, TokenID, TokenTransferList, TopicID, TransactionID, TransferList } from "./basic_types_pb.js";
import type { Timestamp, TimestampSeconds } from "./timestamp_pb.js";
import type { AssessedCustomFee } from "./custom_fees_pb.js";
import type { ResponseHeader } from "./common_pb.js";

/**
 * Describes the file receipt_record.proto.
 */
export declare const file_receipt_record: GenFile;

/**
 * @generated from message proto.TransactionReceipt
 */
export declare type TransactionReceipt = Message<"proto.TransactionReceipt"> & {
  /**
   * @generated from field: proto.ResponseCodeEnum status = 1;
   */
  status: ResponseCodeEnum;

  /**
   * @generated from field: proto.AccountID accountID = 2;
   */
  accountID?: AccountID;

  /**
   * @generated from field: proto.FileID fileID = 3;
   */
  fileID?: FileID;

  /**
   * @generated from field: proto.ContractID contractID = 4;
   */
  contractID?: ContractID;

  /**
   * @generated from field: proto.ExchangeRate exchangeRate = 5;
   */
  exchangeRate?: ExchangeRate;

  /**
   * @generated from field: proto.TopicID topicID = 6;
   */
  topicID?: TopicID;

  /**
   * @generated from field: uint64 topicSequenceNumber = 7;
   */
  topicSequenceNumber: bigint;

  /**
   * @generated from field: bytes topicRunningHash = 8;
   */
  topicRunningHash: Uint8Array;

  /**
   * @generated from field: uint64 topicRunningHashVersion = 9;
   */
  topicRunningHashVersion: bigint;

  /**
   * @generated from field: proto.TokenID tokenID = 10;
   */
  tokenID?: TokenID;

  /**
   * @generated from field: uint64 newTotalSupply = 11;
   */
  newTotalSupply: bigint;

  /**
   * @generated from field: proto.ScheduleID scheduleID = 12;
   */
  scheduleID?: ScheduleID;

  /**
   * @generated from field: proto.TransactionID scheduledTransactionID = 13;
   */
  scheduledTransactionID?: TransactionID;

  /**
   * @generated from field: repeated int64 serialNumbers = 14;
   */
  serialNumbers: bigint[];

  /**
   * @generated from field: proto.NodeID node_id = 15;
   */
  nodeId?: NodeID;
};

/**
 * Describes the message proto.TransactionReceipt.
 * Use `create(TransactionReceiptSchema)` to create a new message.
 */
export declare const TransactionReceiptSchema: GenMessage<TransactionReceipt>;

/**
 * @generated from message proto.NodeID
 */
export declare type NodeID = Message<"proto.NodeID"> & {
  /**
   * @generated from field: uint64 node_id = 1;
   */
  nodeId: bigint;
};

/**
 * Describes the message proto.NodeID.
 * Use `create(NodeIDSchema)` to create a new message.
 */
export declare const NodeIDSchema: GenMessage<NodeID>;

/**
 * @generated from message proto.ExchangeRate
 */
export declare type ExchangeRate = Message<"proto.ExchangeRate"> & {
  /**
   * @generated from field: int32 hbarEquiv = 1;
   */
  hbarEquiv: number;

  /**
   * @generated from field: int32 centEquiv = 2;
   */
  centEquiv: number;

  /**
   * @generated from field: proto.TimestampSeconds expirationTime = 3;
   */
  expirationTime?: TimestampSeconds;
};

/**
 * Describes the message proto.ExchangeRate.
 * Use `create(ExchangeRateSchema)` to create a new message.
 */
export declare const ExchangeRateSchema: GenMessage<ExchangeRate>;

/**
 * @generated from message proto.ExchangeRateSet
 */
export declare type ExchangeRateSet = Message<"proto.ExchangeRateSet"> & {
  /**
   * @generated from field: proto.ExchangeRate currentRate = 1;
   */
  currentRate?: ExchangeRate;

  /**
   * @generated from field: proto.ExchangeRate nextRate = 2;
   */
  nextRate?: ExchangeRate;
};

/**
 * Describes the message proto.ExchangeRateSet.
 * Use `create(ExchangeRateSetSchema)` to create a new message.
 */
export declare const ExchangeRateSetSchema: GenMessage<ExchangeRateSet>;

/**
 * @generated from message proto.ContractFunctionResult
 */
export declare type ContractFunctionResult = Message<"proto.ContractFunctionResult"> & {
  /**
   * @generated from field: proto.ContractID contractID = 1;
   */
  contractID?: ContractID;

  /**
   * @generated from field: bytes contractCallResult = 2;
   */
  contractCallResult: Uint8Array;

  /**
   * @generated from field: string errorMessage = 3;
   */
  errorMessage: string;

  /**
   * @generated from field: bytes bloom = 4;
   */
  bloom: Uint8Array;

  /**
   * @generated from field: uint64 gasUsed = 5;
   */
  gasUsed: bigint;

  /**
   * @generated from field: repeated proto.ContractLoginfo logInfo = 6;
   */
  logInfo: ContractLoginfo[];

  /**
   * @generated from field: bytes evm_address = 9;
   */
  evmAddress: Uint8Array;

  /**
   * @generated from field: int64 gas = 10;
   */
  gas: bigint;

  /**
   * @generated from field: int64 amount = 11;
   */
  amount: bigint;

  /**
   * @generated from field: bytes functionParameters = 12;
   */
  functionParameters: Uint8Array;

  /**
   * @generated from field: proto.AccountID sender_id = 13;
   */
  senderId?: AccountID;
};

/**
 * Describes the message proto.ContractFunctionResult.
 * Use `create(ContractFunctionResultSchema)` to create a new message.
 */
export declare const ContractFunctionResultSchema: GenMessage<ContractFunctionResult>;

/**
 * @generated from message proto.ContractLoginfo
 */
export declare type ContractLoginfo = Message<"proto.ContractLoginfo"> & {
  /**
   * @generated from field: proto.ContractID contractID = 1;
   */
  contractID?: ContractID;

  /**
   * @generated from field: bytes bloom = 2;
   */
  bloom: Uint8Array;

  /**
   * @generated from field: repeated bytes topic = 3;
   */
  topic: Uint8Array[];

  /**
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;
};

/**
 * Describes the message proto.ContractLoginfo.
 * Use `create(ContractLoginfoSchema)` to create a new message.
 */
export declare const ContractLoginfoSchema: GenMessage<ContractLoginfo>;

/**
 * @generated from message proto.TransactionRecord
 */
export declare type TransactionRecord = Message<"proto.TransactionRecord"> & {
  /**
   * @generated from field: proto.TransactionReceipt receipt = 1;
   */
  receipt?: TransactionReceipt;

  /**
   * @generated from field: bytes transactionHash = 2;
   */
  transactionHash: Uint8Array;

  /**
   * @generated from field: proto.Timestamp consensusTimestamp = 3;
   */
  consensusTimestamp?: Timestamp;

  /**
   * @generated from field: proto.TransactionID transactionID = 4;
   */
  transactionID?: TransactionID;

  /**
   * @generated from field: string memo = 5;
   */
  memo: string;

  /**
   * @generated from field: uint64 transactionFee = 6;
   */
  transactionFee: bigint;

  /**
   * @generated from oneof proto.TransactionRecord.body
   */
  body: {
    /**
     * @generated from field: proto.ContractFunctionResult contractCallResult = 7;
     */
    value: ContractFunctionResult;
    case: "contractCallResult";
  } | {
    /**
     * @generated from field: proto.ContractFunctionResult contractCreateResult = 8;
     */
    value: ContractFunctionResult;
    case: "contractCreateResult";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: proto.TransferList transferList = 10;
   */
  transferList?: TransferList;

  /**
   * @generated from field: repeated proto.TokenTransferList tokenTransferLists = 11;
   */
  tokenTransferLists: TokenTransferList[];

  /**
   * @generated from field: proto.ScheduleID scheduleRef = 12;
   */
  scheduleRef?: ScheduleID;

  /**
   * @generated from field: repeated proto.AssessedCustomFee assessed_custom_fees = 13;
   */
  assessedCustomFees: AssessedCustomFee[];

  /**
   * @generated from field: repeated proto.TokenAssociation automatic_token_associations = 14;
   */
  automaticTokenAssociations: TokenAssociation[];

  /**
   * @generated from field: proto.Timestamp parent_consensus_timestamp = 15;
   */
  parentConsensusTimestamp?: Timestamp;

  /**
   * @generated from field: bytes alias = 16;
   */
  alias: Uint8Array;

  /**
   * @generated from field: bytes ethereum_hash = 17;
   */
  ethereumHash: Uint8Array;

  /**
   * @generated from field: repeated proto.TokenTransferList paid_staking_rewards = 18;
   */
  paidStakingRewards: TokenTransferList[];

  /**
   * @generated from field: bytes evm_address = 21;
   */
  evmAddress: Uint8Array;
};

/**
 * Describes the message proto.TransactionRecord.
 * Use `create(TransactionRecordSchema)` to create a new message.
 */
export declare const TransactionRecordSchema: GenMessage<TransactionRecord>;

/**
 * @generated from message proto.TransactionGetReceiptResponse
 */
export declare type TransactionGetReceiptResponse = Message<"proto.TransactionGetReceiptResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.TransactionReceipt receipt = 2;
   */
  receipt?: TransactionReceipt;

  /**
   * @generated from field: repeated proto.TransactionReceipt duplicateTransactionReceipts = 4;
   */
  duplicateTransactionReceipts: TransactionReceipt[];

  /**
   * @generated from field: repeated proto.TransactionReceipt child_transaction_receipts = 5;
   */
  childTransactionReceipts: TransactionReceipt[];
};

/**
 * Describes the message proto.TransactionGetReceiptResponse.
 * Use `create(TransactionGetReceiptResponseSchema)` to create a new message.
 */
export declare const TransactionGetReceiptResponseSchema: GenMessage<TransactionGetReceiptResponse>;

/**
 * @generated from message proto.TransactionGetRecordResponse
 */
export declare type TransactionGetRecordResponse = Message<"proto.TransactionGetRecordResponse"> & {
  /**
   * @generated from field: proto.ResponseHeader header = 1;
   */
  header?: ResponseHeader;

  /**
   * @generated from field: proto.TransactionRecord transactionRecord = 3;
   */
  transactionRecord?: TransactionRecord;

  /**
   * @generated from field: repeated proto.TransactionRecord duplicateTransactionRecords = 4;
   */
  duplicateTransactionRecords: TransactionRecord[];

  /**
   * @generated from field: repeated proto.TransactionRecord child_transaction_records = 5;
   */
  childTransactionRecords: TransactionRecord[];
};

/**
 * Describes the message proto.TransactionGetRecordResponse.
 * Use `create(TransactionGetRecordResponseSchema)` to create a new message.
 */
export declare const TransactionGetRecordResponseSchema: GenMessage<TransactionGetRecordResponse>;

