//*
// # Response Code Enumeration
// An enumeration of possible response codes.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file response_code.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file response_code.proto.
 */
export declare const file_response_code: GenFile;

/**
 * *
 * An enumeration of possible response codes.
 *
 * @generated from enum proto.ResponseCodeEnum
 */
export enum ResponseCodeEnum {
  /**
   * *
   * The transaction passed the precheck validations.
   *
   * @generated from enum value: OK = 0;
   */
  OK = 0,

  /**
   * *
   * For any error not handled by specific error codes listed below.
   *
   * @generated from enum value: INVALID_TRANSACTION = 1;
   */
  INVALID_TRANSACTION = 1,

  /**
   * *
   * Payer account does not exist.
   *
   * @generated from enum value: PAYER_ACCOUNT_NOT_FOUND = 2;
   */
  PAYER_ACCOUNT_NOT_FOUND = 2,

  /**
   * *
   * Node Account provided does not match the node account of the node the transaction was submitted
   * to.
   *
   * @generated from enum value: INVALID_NODE_ACCOUNT = 3;
   */
  INVALID_NODE_ACCOUNT = 3,

  /**
   * *
   * Pre-Check error when TransactionValidStart + transactionValidDuration is less than current
   * consensus time.
   *
   * @generated from enum value: TRANSACTION_EXPIRED = 4;
   */
  TRANSACTION_EXPIRED = 4,

  /**
   * *
   * Transaction start time is greater than current consensus time
   *
   * @generated from enum value: INVALID_TRANSACTION_START = 5;
   */
  INVALID_TRANSACTION_START = 5,

  /**
   * *
   * The given transactionValidDuration was either non-positive, or greater than the maximum
   * valid duration of 180 secs.
   *
   *
   * @generated from enum value: INVALID_TRANSACTION_DURATION = 6;
   */
  INVALID_TRANSACTION_DURATION = 6,

  /**
   * *
   * The transaction signature is not valid
   *
   * @generated from enum value: INVALID_SIGNATURE = 7;
   */
  INVALID_SIGNATURE = 7,

  /**
   * *
   * Transaction memo size exceeded 100 bytes
   *
   * @generated from enum value: MEMO_TOO_LONG = 8;
   */
  MEMO_TOO_LONG = 8,

  /**
   * *
   * The fee provided in the transaction is insufficient for this type of transaction
   *
   * @generated from enum value: INSUFFICIENT_TX_FEE = 9;
   */
  INSUFFICIENT_TX_FEE = 9,

  /**
   * *
   * The payer account has insufficient cryptocurrency to pay the transaction fee
   *
   * @generated from enum value: INSUFFICIENT_PAYER_BALANCE = 10;
   */
  INSUFFICIENT_PAYER_BALANCE = 10,

  /**
   * *
   * This transaction ID is a duplicate of one that was submitted to this node or reached consensus
   * in the last 180 seconds (receipt period)
   *
   * @generated from enum value: DUPLICATE_TRANSACTION = 11;
   */
  DUPLICATE_TRANSACTION = 11,

  /**
   * *
   * If API is throttled out
   *
   * @generated from enum value: BUSY = 12;
   */
  BUSY = 12,

  /**
   * *
   * The API is not currently supported
   *
   * @generated from enum value: NOT_SUPPORTED = 13;
   */
  NOT_SUPPORTED = 13,

  /**
   * *
   * The file id is invalid or does not exist
   *
   * @generated from enum value: INVALID_FILE_ID = 14;
   */
  INVALID_FILE_ID = 14,

  /**
   * *
   * The account id is invalid or does not exist
   *
   * @generated from enum value: INVALID_ACCOUNT_ID = 15;
   */
  INVALID_ACCOUNT_ID = 15,

  /**
   * *
   * The contract id is invalid or does not exist
   *
   * @generated from enum value: INVALID_CONTRACT_ID = 16;
   */
  INVALID_CONTRACT_ID = 16,

  /**
   * *
   * Transaction id is not valid
   *
   * @generated from enum value: INVALID_TRANSACTION_ID = 17;
   */
  INVALID_TRANSACTION_ID = 17,

  /**
   * *
   * Receipt for given transaction id does not exist
   *
   * @generated from enum value: RECEIPT_NOT_FOUND = 18;
   */
  RECEIPT_NOT_FOUND = 18,

  /**
   * *
   * Record for given transaction id does not exist
   *
   * @generated from enum value: RECORD_NOT_FOUND = 19;
   */
  RECORD_NOT_FOUND = 19,

  /**
   * *
   * The solidity id is invalid or entity with this solidity id does not exist
   *
   * @generated from enum value: INVALID_SOLIDITY_ID = 20;
   */
  INVALID_SOLIDITY_ID = 20,

  /**
   * *
   * The responding node has submitted the transaction to the network. Its final status is still
   * unknown.
   *
   * @generated from enum value: UNKNOWN = 21;
   */
  UNKNOWN = 21,

  /**
   * *
   * The transaction succeeded
   *
   * @generated from enum value: SUCCESS = 22;
   */
  SUCCESS = 22,

  /**
   * *
   * There was a system error and the transaction failed because of invalid request parameters.
   *
   * @generated from enum value: FAIL_INVALID = 23;
   */
  FAIL_INVALID = 23,

  /**
   * *
   * There was a system error while performing fee calculation, reserved for future.
   *
   * @generated from enum value: FAIL_FEE = 24;
   */
  FAIL_FEE = 24,

  /**
   * *
   * There was a system error while performing balance checks, reserved for future.
   *
   * @generated from enum value: FAIL_BALANCE = 25;
   */
  FAIL_BALANCE = 25,

  /**
   * *
   * Key not provided in the transaction body
   *
   * @generated from enum value: KEY_REQUIRED = 26;
   */
  KEY_REQUIRED = 26,

  /**
   * *
   * Unsupported algorithm/encoding used for keys in the transaction
   *
   * @generated from enum value: BAD_ENCODING = 27;
   */
  BAD_ENCODING = 27,

  /**
   * *
   * When the account balance is not sufficient for the transfer
   *
   * @generated from enum value: INSUFFICIENT_ACCOUNT_BALANCE = 28;
   */
  INSUFFICIENT_ACCOUNT_BALANCE = 28,

  /**
   * *
   * During an update transaction when the system is not able to find the Users Solidity address
   *
   * @generated from enum value: INVALID_SOLIDITY_ADDRESS = 29;
   */
  INVALID_SOLIDITY_ADDRESS = 29,

  /**
   * *
   * Not enough gas was supplied to execute transaction
   *
   * @generated from enum value: INSUFFICIENT_GAS = 30;
   */
  INSUFFICIENT_GAS = 30,

  /**
   * *
   * contract byte code size is over the limit
   *
   * @generated from enum value: CONTRACT_SIZE_LIMIT_EXCEEDED = 31;
   */
  CONTRACT_SIZE_LIMIT_EXCEEDED = 31,

  /**
   * *
   * local execution (query) is requested for a function which changes state
   *
   * @generated from enum value: LOCAL_CALL_MODIFICATION_EXCEPTION = 32;
   */
  LOCAL_CALL_MODIFICATION_EXCEPTION = 32,

  /**
   * *
   * Contract REVERT OPCODE executed
   *
   * @generated from enum value: CONTRACT_REVERT_EXECUTED = 33;
   */
  CONTRACT_REVERT_EXECUTED = 33,

  /**
   * *
   * For any contract execution related error not handled by specific error codes listed above.
   *
   * @generated from enum value: CONTRACT_EXECUTION_EXCEPTION = 34;
   */
  CONTRACT_EXECUTION_EXCEPTION = 34,

  /**
   * *
   * In Query validation, account with +ve(amount) value should be Receiving node account, the
   * receiver account should be only one account in the list
   *
   * @generated from enum value: INVALID_RECEIVING_NODE_ACCOUNT = 35;
   */
  INVALID_RECEIVING_NODE_ACCOUNT = 35,

  /**
   * *
   * Header is missing in Query request
   *
   * @generated from enum value: MISSING_QUERY_HEADER = 36;
   */
  MISSING_QUERY_HEADER = 36,

  /**
   * *
   * The update of the account failed
   *
   * @generated from enum value: ACCOUNT_UPDATE_FAILED = 37;
   */
  ACCOUNT_UPDATE_FAILED = 37,

  /**
   * *
   * Provided key encoding was not supported by the system
   *
   * @generated from enum value: INVALID_KEY_ENCODING = 38;
   */
  INVALID_KEY_ENCODING = 38,

  /**
   * *
   * null solidity address
   *
   * @generated from enum value: NULL_SOLIDITY_ADDRESS = 39;
   */
  NULL_SOLIDITY_ADDRESS = 39,

  /**
   * *
   * update of the contract failed
   *
   * @generated from enum value: CONTRACT_UPDATE_FAILED = 40;
   */
  CONTRACT_UPDATE_FAILED = 40,

  /**
   * *
   * the query header is invalid
   *
   * @generated from enum value: INVALID_QUERY_HEADER = 41;
   */
  INVALID_QUERY_HEADER = 41,

  /**
   * *
   * Invalid fee submitted
   *
   * @generated from enum value: INVALID_FEE_SUBMITTED = 42;
   */
  INVALID_FEE_SUBMITTED = 42,

  /**
   * *
   * Payer signature is invalid
   *
   * @generated from enum value: INVALID_PAYER_SIGNATURE = 43;
   */
  INVALID_PAYER_SIGNATURE = 43,

  /**
   * *
   * The keys were not provided in the request.
   *
   * @generated from enum value: KEY_NOT_PROVIDED = 44;
   */
  KEY_NOT_PROVIDED = 44,

  /**
   * *
   * Expiration time provided in the transaction was invalid.
   *
   * @generated from enum value: INVALID_EXPIRATION_TIME = 45;
   */
  INVALID_EXPIRATION_TIME = 45,

  /**
   * *
   * WriteAccess Control Keys are not provided for the file
   *
   * @generated from enum value: NO_WACL_KEY = 46;
   */
  NO_WACL_KEY = 46,

  /**
   * *
   * The contents of file are provided as empty.
   *
   * @generated from enum value: FILE_CONTENT_EMPTY = 47;
   */
  FILE_CONTENT_EMPTY = 47,

  /**
   * *
   * The crypto transfer credit and debit do not sum equal to 0
   *
   * @generated from enum value: INVALID_ACCOUNT_AMOUNTS = 48;
   */
  INVALID_ACCOUNT_AMOUNTS = 48,

  /**
   * *
   * Transaction body provided is empty
   *
   * @generated from enum value: EMPTY_TRANSACTION_BODY = 49;
   */
  EMPTY_TRANSACTION_BODY = 49,

  /**
   * *
   * Invalid transaction body provided
   *
   * @generated from enum value: INVALID_TRANSACTION_BODY = 50;
   */
  INVALID_TRANSACTION_BODY = 50,

  /**
   * *
   * the type of key (base ed25519 key, KeyList, or ThresholdKey) does not match the type of
   * signature (base ed25519 signature, SignatureList, or ThresholdKeySignature)
   *
   * @generated from enum value: INVALID_SIGNATURE_TYPE_MISMATCHING_KEY = 51;
   */
  INVALID_SIGNATURE_TYPE_MISMATCHING_KEY = 51,

  /**
   * *
   * the number of key (KeyList, or ThresholdKey) does not match that of signature (SignatureList,
   * or ThresholdKeySignature). e.g. if a keyList has 3 base keys, then the corresponding
   * signatureList should also have 3 base signatures.
   *
   * @generated from enum value: INVALID_SIGNATURE_COUNT_MISMATCHING_KEY = 52;
   */
  INVALID_SIGNATURE_COUNT_MISMATCHING_KEY = 52,

  /**
   * *
   * the livehash body is empty
   *
   * @generated from enum value: EMPTY_LIVE_HASH_BODY = 53;
   */
  EMPTY_LIVE_HASH_BODY = 53,

  /**
   * *
   * the livehash data is missing
   *
   * @generated from enum value: EMPTY_LIVE_HASH = 54;
   */
  EMPTY_LIVE_HASH = 54,

  /**
   * *
   * the keys for a livehash are missing
   *
   * @generated from enum value: EMPTY_LIVE_HASH_KEYS = 55;
   */
  EMPTY_LIVE_HASH_KEYS = 55,

  /**
   * *
   * the livehash data is not the output of a SHA-384 digest
   *
   * @generated from enum value: INVALID_LIVE_HASH_SIZE = 56;
   */
  INVALID_LIVE_HASH_SIZE = 56,

  /**
   * *
   * the query body is empty
   *
   * @generated from enum value: EMPTY_QUERY_BODY = 57;
   */
  EMPTY_QUERY_BODY = 57,

  /**
   * *
   * the crypto livehash query is empty
   *
   * @generated from enum value: EMPTY_LIVE_HASH_QUERY = 58;
   */
  EMPTY_LIVE_HASH_QUERY = 58,

  /**
   * *
   * the livehash is not present
   *
   * @generated from enum value: LIVE_HASH_NOT_FOUND = 59;
   */
  LIVE_HASH_NOT_FOUND = 59,

  /**
   * *
   * the account id passed has not yet been created.
   *
   * @generated from enum value: ACCOUNT_ID_DOES_NOT_EXIST = 60;
   */
  ACCOUNT_ID_DOES_NOT_EXIST = 60,

  /**
   * *
   * the livehash already exists for a given account
   *
   * @generated from enum value: LIVE_HASH_ALREADY_EXISTS = 61;
   */
  LIVE_HASH_ALREADY_EXISTS = 61,

  /**
   * *
   * File WACL keys are invalid
   *
   * @generated from enum value: INVALID_FILE_WACL = 62;
   */
  INVALID_FILE_WACL = 62,

  /**
   * *
   * Serialization failure
   *
   * @generated from enum value: SERIALIZATION_FAILED = 63;
   */
  SERIALIZATION_FAILED = 63,

  /**
   * *
   * The size of the Transaction is greater than transactionMaxBytes
   *
   * @generated from enum value: TRANSACTION_OVERSIZE = 64;
   */
  TRANSACTION_OVERSIZE = 64,

  /**
   * *
   * The Transaction has more than 50 levels
   *
   * @generated from enum value: TRANSACTION_TOO_MANY_LAYERS = 65;
   */
  TRANSACTION_TOO_MANY_LAYERS = 65,

  /**
   * *
   * Contract is marked as deleted
   *
   * @generated from enum value: CONTRACT_DELETED = 66;
   */
  CONTRACT_DELETED = 66,

  /**
   * *
   * the platform node is either disconnected or lagging behind.
   *
   * @generated from enum value: PLATFORM_NOT_ACTIVE = 67;
   */
  PLATFORM_NOT_ACTIVE = 67,

  /**
   * *
   * one public key matches more than one prefixes on the signature map
   *
   * @generated from enum value: KEY_PREFIX_MISMATCH = 68;
   */
  KEY_PREFIX_MISMATCH = 68,

  /**
   * *
   * transaction not created by platform due to large backlog
   *
   * @generated from enum value: PLATFORM_TRANSACTION_NOT_CREATED = 69;
   */
  PLATFORM_TRANSACTION_NOT_CREATED = 69,

  /**
   * *
   * auto renewal period is not a positive number of seconds
   *
   * @generated from enum value: INVALID_RENEWAL_PERIOD = 70;
   */
  INVALID_RENEWAL_PERIOD = 70,

  /**
   * *
   * the response code when a smart contract id is passed for a crypto API request
   *
   * @generated from enum value: INVALID_PAYER_ACCOUNT_ID = 71;
   */
  INVALID_PAYER_ACCOUNT_ID = 71,

  /**
   * *
   * the account has been marked as deleted
   *
   * @generated from enum value: ACCOUNT_DELETED = 72;
   */
  ACCOUNT_DELETED = 72,

  /**
   * *
   * the file has been marked as deleted
   *
   * @generated from enum value: FILE_DELETED = 73;
   */
  FILE_DELETED = 73,

  /**
   * *
   * same accounts repeated in the transfer account list
   *
   * @generated from enum value: ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS = 74;
   */
  ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS = 74,

  /**
   * *
   * attempting to set negative balance value for crypto account
   *
   * @generated from enum value: SETTING_NEGATIVE_ACCOUNT_BALANCE = 75;
   */
  SETTING_NEGATIVE_ACCOUNT_BALANCE = 75,

  /**
   * *
   * when deleting smart contract that has crypto balance either transfer account or transfer smart
   * contract is required
   *
   * @generated from enum value: OBTAINER_REQUIRED = 76;
   */
  OBTAINER_REQUIRED = 76,

  /**
   * *
   * when deleting smart contract that has crypto balance you can not use the same contract id as
   * transferContractId as the one being deleted
   *
   * @generated from enum value: OBTAINER_SAME_CONTRACT_ID = 77;
   */
  OBTAINER_SAME_CONTRACT_ID = 77,

  /**
   * *
   * transferAccountId or transferContractId specified for contract delete does not exist
   *
   * @generated from enum value: OBTAINER_DOES_NOT_EXIST = 78;
   */
  OBTAINER_DOES_NOT_EXIST = 78,

  /**
   * *
   * attempting to modify (update or delete a immutable smart contract, i.e. one created without a
   * admin key)
   *
   * @generated from enum value: MODIFYING_IMMUTABLE_CONTRACT = 79;
   */
  MODIFYING_IMMUTABLE_CONTRACT = 79,

  /**
   * *
   * Unexpected exception thrown by file system functions
   *
   * @generated from enum value: FILE_SYSTEM_EXCEPTION = 80;
   */
  FILE_SYSTEM_EXCEPTION = 80,

  /**
   * *
   * the duration is not a subset of [MINIMUM_AUTORENEW_DURATION,MAXIMUM_AUTORENEW_DURATION]
   *
   * @generated from enum value: AUTORENEW_DURATION_NOT_IN_RANGE = 81;
   */
  AUTORENEW_DURATION_NOT_IN_RANGE = 81,

  /**
   * *
   * Decoding the smart contract binary to a byte array failed. Check that the input is a valid hex
   * string.
   *
   * @generated from enum value: ERROR_DECODING_BYTESTRING = 82;
   */
  ERROR_DECODING_BYTESTRING = 82,

  /**
   * *
   * File to create a smart contract was of length zero
   *
   * @generated from enum value: CONTRACT_FILE_EMPTY = 83;
   */
  CONTRACT_FILE_EMPTY = 83,

  /**
   * *
   * Bytecode for smart contract is of length zero
   *
   * @generated from enum value: CONTRACT_BYTECODE_EMPTY = 84;
   */
  CONTRACT_BYTECODE_EMPTY = 84,

  /**
   * *
   * Attempt to set negative initial balance
   *
   * @generated from enum value: INVALID_INITIAL_BALANCE = 85;
   */
  INVALID_INITIAL_BALANCE = 85,

  /**
   * *
   * Attempt to set negative receive record threshold
   *
   * @generated from enum value: INVALID_RECEIVE_RECORD_THRESHOLD = 86 [deprecated = true];
   * @deprecated
   */
  INVALID_RECEIVE_RECORD_THRESHOLD = 86,

  /**
   * *
   * Attempt to set negative send record threshold
   *
   * @generated from enum value: INVALID_SEND_RECORD_THRESHOLD = 87 [deprecated = true];
   * @deprecated
   */
  INVALID_SEND_RECORD_THRESHOLD = 87,

  /**
   * *
   * Special Account Operations should be performed by only Genesis account, return this code if it
   * is not Genesis Account
   *
   * @generated from enum value: ACCOUNT_IS_NOT_GENESIS_ACCOUNT = 88;
   */
  ACCOUNT_IS_NOT_GENESIS_ACCOUNT = 88,

  /**
   * *
   * The fee payer account doesn't have permission to submit such Transaction
   *
   * @generated from enum value: PAYER_ACCOUNT_UNAUTHORIZED = 89;
   */
  PAYER_ACCOUNT_UNAUTHORIZED = 89,

  /**
   * *
   * FreezeTransactionBody is invalid
   *
   * @generated from enum value: INVALID_FREEZE_TRANSACTION_BODY = 90;
   */
  INVALID_FREEZE_TRANSACTION_BODY = 90,

  /**
   * *
   * FreezeTransactionBody does not exist
   *
   * @generated from enum value: FREEZE_TRANSACTION_BODY_NOT_FOUND = 91;
   */
  FREEZE_TRANSACTION_BODY_NOT_FOUND = 91,

  /**
   * *
   * Exceeded the number of accounts (both from and to) allowed for crypto transfer list
   *
   * @generated from enum value: TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 92;
   */
  TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 92,

  /**
   * *
   * Smart contract result size greater than specified maxResultSize
   *
   * @generated from enum value: RESULT_SIZE_LIMIT_EXCEEDED = 93;
   */
  RESULT_SIZE_LIMIT_EXCEEDED = 93,

  /**
   * *
   * The payer account is not a special account(account 0.0.55)
   *
   * @generated from enum value: NOT_SPECIAL_ACCOUNT = 94;
   */
  NOT_SPECIAL_ACCOUNT = 94,

  /**
   * *
   * Negative gas was offered in smart contract call
   *
   * @generated from enum value: CONTRACT_NEGATIVE_GAS = 95;
   */
  CONTRACT_NEGATIVE_GAS = 95,

  /**
   * *
   * Negative value / initial balance was specified in a smart contract call / create
   *
   * @generated from enum value: CONTRACT_NEGATIVE_VALUE = 96;
   */
  CONTRACT_NEGATIVE_VALUE = 96,

  /**
   * *
   * Failed to update fee file
   *
   * @generated from enum value: INVALID_FEE_FILE = 97;
   */
  INVALID_FEE_FILE = 97,

  /**
   * *
   * Failed to update exchange rate file
   *
   * @generated from enum value: INVALID_EXCHANGE_RATE_FILE = 98;
   */
  INVALID_EXCHANGE_RATE_FILE = 98,

  /**
   * *
   * Payment tendered for contract local call cannot cover both the fee and the gas
   *
   * @generated from enum value: INSUFFICIENT_LOCAL_CALL_GAS = 99;
   */
  INSUFFICIENT_LOCAL_CALL_GAS = 99,

  /**
   * *
   * Entities with Entity ID below 1000 are not allowed to be deleted
   *
   * @generated from enum value: ENTITY_NOT_ALLOWED_TO_DELETE = 100;
   */
  ENTITY_NOT_ALLOWED_TO_DELETE = 100,

  /**
   * *
   * Violating one of these rules: 1) treasury account can update all entities below 0.0.1000, 2)
   * account 0.0.50 can update all entities from 0.0.51 - 0.0.80, 3) Network Function Master Account
   * A/c 0.0.50 - Update all Network Function accounts & perform all the Network Functions listed
   * below, 4) Network Function Accounts: i) A/c 0.0.55 - Update Address Book files (0.0.101/102),
   * ii) A/c 0.0.56 - Update Fee schedule (0.0.111), iii) A/c 0.0.57 - Update Exchange Rate
   * (0.0.112).
   *
   * @generated from enum value: AUTHORIZATION_FAILED = 101;
   */
  AUTHORIZATION_FAILED = 101,

  /**
   * *
   * Fee Schedule Proto uploaded but not valid (append or update is required)
   *
   * @generated from enum value: FILE_UPLOADED_PROTO_INVALID = 102;
   */
  FILE_UPLOADED_PROTO_INVALID = 102,

  /**
   * *
   * Fee Schedule Proto uploaded but not valid (append or update is required)
   *
   * @generated from enum value: FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK = 103;
   */
  FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK = 103,

  /**
   * *
   * Fee Schedule Proto File Part uploaded
   *
   * @generated from enum value: FEE_SCHEDULE_FILE_PART_UPLOADED = 104;
   */
  FEE_SCHEDULE_FILE_PART_UPLOADED = 104,

  /**
   * *
   * The change on Exchange Rate exceeds Exchange_Rate_Allowed_Percentage
   *
   * @generated from enum value: EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED = 105;
   */
  EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED = 105,

  /**
   * *
   * Contract permanent storage exceeded the currently allowable limit
   *
   * @generated from enum value: MAX_CONTRACT_STORAGE_EXCEEDED = 106;
   */
  MAX_CONTRACT_STORAGE_EXCEEDED = 106,

  /**
   * *
   * Transfer Account should not be same as Account to be deleted
   *
   * @generated from enum value: TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT = 107;
   */
  TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT = 107,

  /**
   * @generated from enum value: TOTAL_LEDGER_BALANCE_INVALID = 108;
   */
  TOTAL_LEDGER_BALANCE_INVALID = 108,

  /**
   * *
   * The expiration date/time on a smart contract may not be reduced
   *
   * @generated from enum value: EXPIRATION_REDUCTION_NOT_ALLOWED = 110;
   */
  EXPIRATION_REDUCTION_NOT_ALLOWED = 110,

  /**
   * *
   * Gas exceeded currently allowable gas limit per transaction
   *
   * @generated from enum value: MAX_GAS_LIMIT_EXCEEDED = 111;
   */
  MAX_GAS_LIMIT_EXCEEDED = 111,

  /**
   * *
   * File size exceeded the currently allowable limit
   *
   * @generated from enum value: MAX_FILE_SIZE_EXCEEDED = 112;
   */
  MAX_FILE_SIZE_EXCEEDED = 112,

  /**
   * *
   * When a valid signature is not provided for operations on account with receiverSigRequired=true
   *
   * @generated from enum value: RECEIVER_SIG_REQUIRED = 113;
   */
  RECEIVER_SIG_REQUIRED = 113,

  /**
   * *
   * The Topic ID specified is not in the system.
   *
   * @generated from enum value: INVALID_TOPIC_ID = 150;
   */
  INVALID_TOPIC_ID = 150,

  /**
   * *
   * A provided admin key was invalid. Verify the bytes for an Ed25519 public key are exactly 32 bytes; and the bytes for a compressed ECDSA(secp256k1) key are exactly 33 bytes, with the first byte either 0x02 or 0x03..
   *
   * @generated from enum value: INVALID_ADMIN_KEY = 155;
   */
  INVALID_ADMIN_KEY = 155,

  /**
   * *
   * A provided submit key was invalid.
   *
   * @generated from enum value: INVALID_SUBMIT_KEY = 156;
   */
  INVALID_SUBMIT_KEY = 156,

  /**
   * *
   * An attempted operation was not authorized (ie - a deleteTopic for a topic with no adminKey).
   *
   * @generated from enum value: UNAUTHORIZED = 157;
   */
  UNAUTHORIZED = 157,

  /**
   * *
   * A ConsensusService message is empty.
   *
   * @generated from enum value: INVALID_TOPIC_MESSAGE = 158;
   */
  INVALID_TOPIC_MESSAGE = 158,

  /**
   * *
   * The autoRenewAccount specified is not a valid, active account.
   *
   * @generated from enum value: INVALID_AUTORENEW_ACCOUNT = 159;
   */
  INVALID_AUTORENEW_ACCOUNT = 159,

  /**
   * *
   * An adminKey was not specified on the topic, so there must not be an autoRenewAccount.
   *
   * @generated from enum value: AUTORENEW_ACCOUNT_NOT_ALLOWED = 160;
   */
  AUTORENEW_ACCOUNT_NOT_ALLOWED = 160,

  /**
   * *
   * The topic has expired, was not automatically renewed, and is in a 7 day grace period before the
   * topic will be deleted unrecoverably. This error response code will not be returned until
   * autoRenew functionality is supported by HAPI.
   *
   * @generated from enum value: TOPIC_EXPIRED = 162;
   */
  TOPIC_EXPIRED = 162,

  /**
   * chunk number must be from 1 to total (chunks) inclusive.
   *
   * @generated from enum value: INVALID_CHUNK_NUMBER = 163;
   */
  INVALID_CHUNK_NUMBER = 163,

  /**
   * For every chunk, the payer account that is part of initialTransactionID must match the Payer Account of this transaction. The entire initialTransactionID should match the transactionID of the first chunk, but this is not checked or enforced by Hedera except when the chunk number is 1.
   *
   * @generated from enum value: INVALID_CHUNK_TRANSACTION_ID = 164;
   */
  INVALID_CHUNK_TRANSACTION_ID = 164,

  /**
   * Account is frozen and cannot transact with the token
   *
   * @generated from enum value: ACCOUNT_FROZEN_FOR_TOKEN = 165;
   */
  ACCOUNT_FROZEN_FOR_TOKEN = 165,

  /**
   * An involved account already has more than <tt>tokens.maxPerAccount</tt> associations with non-deleted tokens.
   *
   * @generated from enum value: TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED = 166;
   */
  TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED = 166,

  /**
   * The token is invalid or does not exist
   *
   * @generated from enum value: INVALID_TOKEN_ID = 167;
   */
  INVALID_TOKEN_ID = 167,

  /**
   * Invalid token decimals
   *
   * @generated from enum value: INVALID_TOKEN_DECIMALS = 168;
   */
  INVALID_TOKEN_DECIMALS = 168,

  /**
   * Invalid token initial supply
   *
   * @generated from enum value: INVALID_TOKEN_INITIAL_SUPPLY = 169;
   */
  INVALID_TOKEN_INITIAL_SUPPLY = 169,

  /**
   * Treasury Account does not exist or is deleted
   *
   * @generated from enum value: INVALID_TREASURY_ACCOUNT_FOR_TOKEN = 170;
   */
  INVALID_TREASURY_ACCOUNT_FOR_TOKEN = 170,

  /**
   * Token Symbol is not UTF-8 capitalized alphabetical string
   *
   * @generated from enum value: INVALID_TOKEN_SYMBOL = 171;
   */
  INVALID_TOKEN_SYMBOL = 171,

  /**
   * Freeze key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_FREEZE_KEY = 172;
   */
  TOKEN_HAS_NO_FREEZE_KEY = 172,

  /**
   * Amounts in transfer list are not net zero
   *
   * @generated from enum value: TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN = 173;
   */
  TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN = 173,

  /**
   * A token symbol was not provided
   *
   * @generated from enum value: MISSING_TOKEN_SYMBOL = 174;
   */
  MISSING_TOKEN_SYMBOL = 174,

  /**
   * The provided token symbol was too long
   *
   * @generated from enum value: TOKEN_SYMBOL_TOO_LONG = 175;
   */
  TOKEN_SYMBOL_TOO_LONG = 175,

  /**
   * KYC must be granted and account does not have KYC granted
   *
   * @generated from enum value: ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN = 176;
   */
  ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN = 176,

  /**
   * KYC key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_KYC_KEY = 177;
   */
  TOKEN_HAS_NO_KYC_KEY = 177,

  /**
   * Token balance is not sufficient for the transaction
   *
   * @generated from enum value: INSUFFICIENT_TOKEN_BALANCE = 178;
   */
  INSUFFICIENT_TOKEN_BALANCE = 178,

  /**
   * Token transactions cannot be executed on deleted token
   *
   * @generated from enum value: TOKEN_WAS_DELETED = 179;
   */
  TOKEN_WAS_DELETED = 179,

  /**
   * Supply key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_SUPPLY_KEY = 180;
   */
  TOKEN_HAS_NO_SUPPLY_KEY = 180,

  /**
   * Wipe key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_WIPE_KEY = 181;
   */
  TOKEN_HAS_NO_WIPE_KEY = 181,

  /**
   * The requested token mint amount would cause an invalid total supply
   *
   * @generated from enum value: INVALID_TOKEN_MINT_AMOUNT = 182;
   */
  INVALID_TOKEN_MINT_AMOUNT = 182,

  /**
   * The requested token burn amount would cause an invalid total supply
   *
   * @generated from enum value: INVALID_TOKEN_BURN_AMOUNT = 183;
   */
  INVALID_TOKEN_BURN_AMOUNT = 183,

  /**
   * A required token-account relationship is missing
   *
   * @generated from enum value: TOKEN_NOT_ASSOCIATED_TO_ACCOUNT = 184;
   */
  TOKEN_NOT_ASSOCIATED_TO_ACCOUNT = 184,

  /**
   * The target of a wipe operation was the token treasury account
   *
   * @generated from enum value: CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT = 185;
   */
  CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT = 185,

  /**
   * The provided KYC key was invalid.
   *
   * @generated from enum value: INVALID_KYC_KEY = 186;
   */
  INVALID_KYC_KEY = 186,

  /**
   * The provided wipe key was invalid.
   *
   * @generated from enum value: INVALID_WIPE_KEY = 187;
   */
  INVALID_WIPE_KEY = 187,

  /**
   * The provided freeze key was invalid.
   *
   * @generated from enum value: INVALID_FREEZE_KEY = 188;
   */
  INVALID_FREEZE_KEY = 188,

  /**
   * The provided supply key was invalid.
   *
   * @generated from enum value: INVALID_SUPPLY_KEY = 189;
   */
  INVALID_SUPPLY_KEY = 189,

  /**
   * Token Name is not provided
   *
   * @generated from enum value: MISSING_TOKEN_NAME = 190;
   */
  MISSING_TOKEN_NAME = 190,

  /**
   * Token Name is too long
   *
   * @generated from enum value: TOKEN_NAME_TOO_LONG = 191;
   */
  TOKEN_NAME_TOO_LONG = 191,

  /**
   * The provided wipe amount must not be negative, zero or bigger than the token holder balance
   *
   * @generated from enum value: INVALID_WIPING_AMOUNT = 192;
   */
  INVALID_WIPING_AMOUNT = 192,

  /**
   * Token does not have Admin key set, thus update/delete transactions cannot be performed
   *
   * @generated from enum value: TOKEN_IS_IMMUTABLE = 193;
   */
  TOKEN_IS_IMMUTABLE = 193,

  /**
   * An <tt>associateToken</tt> operation specified a token already associated to the account
   *
   * @generated from enum value: TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT = 194;
   */
  TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT = 194,

  /**
   * An attempted operation is invalid until all token balances for the target account are zero
   *
   * @generated from enum value: TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES = 195;
   */
  TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES = 195,

  /**
   * An attempted operation is invalid because the account is a treasury
   *
   * @generated from enum value: ACCOUNT_IS_TREASURY = 196;
   */
  ACCOUNT_IS_TREASURY = 196,

  /**
   * Same TokenIDs present in the token list
   *
   * @generated from enum value: TOKEN_ID_REPEATED_IN_TOKEN_LIST = 197;
   */
  TOKEN_ID_REPEATED_IN_TOKEN_LIST = 197,

  /**
   * Exceeded the number of token transfers (both from and to) allowed for token transfer list
   *
   * @generated from enum value: TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 198;
   */
  TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 198,

  /**
   * TokenTransfersTransactionBody has no TokenTransferList
   *
   * @generated from enum value: EMPTY_TOKEN_TRANSFER_BODY = 199;
   */
  EMPTY_TOKEN_TRANSFER_BODY = 199,

  /**
   * TokenTransfersTransactionBody has a TokenTransferList with no AccountAmounts
   *
   * @generated from enum value: EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS = 200;
   */
  EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS = 200,

  /**
   * *
   * The Scheduled entity does not exist; or has now expired, been deleted, or been executed
   *
   * @generated from enum value: INVALID_SCHEDULE_ID = 201;
   */
  INVALID_SCHEDULE_ID = 201,

  /**
   * *
   * The Scheduled entity cannot be modified. Admin key not set
   *
   * @generated from enum value: SCHEDULE_IS_IMMUTABLE = 202;
   */
  SCHEDULE_IS_IMMUTABLE = 202,

  /**
   * *
   * The provided Scheduled Payer does not exist
   *
   * @generated from enum value: INVALID_SCHEDULE_PAYER_ID = 203;
   */
  INVALID_SCHEDULE_PAYER_ID = 203,

  /**
   * *
   * The Schedule Create Transaction TransactionID account does not exist
   *
   * @generated from enum value: INVALID_SCHEDULE_ACCOUNT_ID = 204;
   */
  INVALID_SCHEDULE_ACCOUNT_ID = 204,

  /**
   * *
   * The provided sig map did not contain any new valid signatures from required signers of the scheduled transaction
   *
   * @generated from enum value: NO_NEW_VALID_SIGNATURES = 205;
   */
  NO_NEW_VALID_SIGNATURES = 205,

  /**
   * *
   * The required signers for a scheduled transaction cannot be resolved, for example because they do not exist or have been deleted
   *
   * @generated from enum value: UNRESOLVABLE_REQUIRED_SIGNERS = 206;
   */
  UNRESOLVABLE_REQUIRED_SIGNERS = 206,

  /**
   * *
   * Only whitelisted transaction types may be scheduled
   *
   * @generated from enum value: SCHEDULED_TRANSACTION_NOT_IN_WHITELIST = 207;
   */
  SCHEDULED_TRANSACTION_NOT_IN_WHITELIST = 207,

  /**
   * *
   * At least one of the signatures in the provided sig map did not represent a valid signature for any required signer
   *
   * @generated from enum value: SOME_SIGNATURES_WERE_INVALID = 208;
   */
  SOME_SIGNATURES_WERE_INVALID = 208,

  /**
   * *
   * The scheduled field in the TransactionID may not be set to true
   *
   * @generated from enum value: TRANSACTION_ID_FIELD_NOT_ALLOWED = 209;
   */
  TRANSACTION_ID_FIELD_NOT_ALLOWED = 209,

  /**
   * *
   * A schedule already exists with the same identifying fields of an attempted ScheduleCreate (that is, all fields other than scheduledPayerAccountID)
   *
   * @generated from enum value: IDENTICAL_SCHEDULE_ALREADY_CREATED = 210;
   */
  IDENTICAL_SCHEDULE_ALREADY_CREATED = 210,

  /**
   * *
   * A string field in the transaction has a UTF-8 encoding with the prohibited zero byte
   *
   * @generated from enum value: INVALID_ZERO_BYTE_IN_STRING = 211;
   */
  INVALID_ZERO_BYTE_IN_STRING = 211,

  /**
   * *
   * A schedule being signed or deleted has already been deleted
   *
   * @generated from enum value: SCHEDULE_ALREADY_DELETED = 212;
   */
  SCHEDULE_ALREADY_DELETED = 212,

  /**
   * *
   * A schedule being signed or deleted has already been executed
   *
   * @generated from enum value: SCHEDULE_ALREADY_EXECUTED = 213;
   */
  SCHEDULE_ALREADY_EXECUTED = 213,

  /**
   * *
   * ConsensusSubmitMessage request's message size is larger than allowed.
   *
   * @generated from enum value: MESSAGE_SIZE_TOO_LARGE = 214;
   */
  MESSAGE_SIZE_TOO_LARGE = 214,

  /**
   * *
   * An operation was assigned to more than one throttle group in a given bucket
   *
   * @generated from enum value: OPERATION_REPEATED_IN_BUCKET_GROUPS = 215;
   */
  OPERATION_REPEATED_IN_BUCKET_GROUPS = 215,

  /**
   * *
   * The capacity needed to satisfy all opsPerSec groups in a bucket overflowed a signed 8-byte integral type
   *
   * @generated from enum value: BUCKET_CAPACITY_OVERFLOW = 216;
   */
  BUCKET_CAPACITY_OVERFLOW = 216,

  /**
   * *
   * Given the network size in the address book, the node-level capacity for an operation would never be enough to accept a single request; usually means a bucket burstPeriod should be increased
   *
   * @generated from enum value: NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION = 217;
   */
  NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION = 217,

  /**
   * *
   * A bucket was defined without any throttle groups
   *
   * @generated from enum value: BUCKET_HAS_NO_THROTTLE_GROUPS = 218;
   */
  BUCKET_HAS_NO_THROTTLE_GROUPS = 218,

  /**
   * *
   * A throttle group was granted zero opsPerSec
   *
   * @generated from enum value: THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC = 219;
   */
  THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC = 219,

  /**
   * *
   * The throttle definitions file was updated, but some supported operations were not assigned a bucket
   *
   * @generated from enum value: SUCCESS_BUT_MISSING_EXPECTED_OPERATION = 220;
   */
  SUCCESS_BUT_MISSING_EXPECTED_OPERATION = 220,

  /**
   * *
   * The new contents for the throttle definitions system file were not valid protobuf
   *
   * @generated from enum value: UNPARSEABLE_THROTTLE_DEFINITIONS = 221;
   */
  UNPARSEABLE_THROTTLE_DEFINITIONS = 221,

  /**
   * *
   * The new throttle definitions system file were invalid, and no more specific error could be divined
   *
   * @generated from enum value: INVALID_THROTTLE_DEFINITIONS = 222;
   */
  INVALID_THROTTLE_DEFINITIONS = 222,

  /**
   * *
   * The transaction references an account which has passed its expiration without renewal funds available, and currently remains in the ledger only because of the grace period given to expired entities
   *
   * @generated from enum value: ACCOUNT_EXPIRED_AND_PENDING_REMOVAL = 223;
   */
  ACCOUNT_EXPIRED_AND_PENDING_REMOVAL = 223,

  /**
   * *
   * Invalid token max supply
   *
   * @generated from enum value: INVALID_TOKEN_MAX_SUPPLY = 224;
   */
  INVALID_TOKEN_MAX_SUPPLY = 224,

  /**
   * *
   * Invalid token nft serial number
   *
   * @generated from enum value: INVALID_TOKEN_NFT_SERIAL_NUMBER = 225;
   */
  INVALID_TOKEN_NFT_SERIAL_NUMBER = 225,

  /**
   * *
   * Invalid nft id
   *
   * @generated from enum value: INVALID_NFT_ID = 226;
   */
  INVALID_NFT_ID = 226,

  /**
   * *
   * Nft metadata is too long
   *
   * @generated from enum value: METADATA_TOO_LONG = 227;
   */
  METADATA_TOO_LONG = 227,

  /**
   * *
   * Repeated operations count exceeds the limit
   *
   * @generated from enum value: BATCH_SIZE_LIMIT_EXCEEDED = 228;
   */
  BATCH_SIZE_LIMIT_EXCEEDED = 228,

  /**
   * *
   * The range of data to be gathered is out of the set boundaries
   *
   * @generated from enum value: INVALID_QUERY_RANGE = 229;
   */
  INVALID_QUERY_RANGE = 229,

  /**
   * *
   * A custom fractional fee set a denominator of zero
   *
   * @generated from enum value: FRACTION_DIVIDES_BY_ZERO = 230;
   */
  FRACTION_DIVIDES_BY_ZERO = 230,

  /**
   * *
   * The transaction payer could not afford a custom fee
   *
   * @generated from enum value: INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE = 231 [deprecated = true];
   * @deprecated
   */
  INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE = 231,

  /**
   * *
   * More than 10 custom fees were specified
   *
   * @generated from enum value: CUSTOM_FEES_LIST_TOO_LONG = 232;
   */
  CUSTOM_FEES_LIST_TOO_LONG = 232,

  /**
   * *
   * Any of the feeCollector accounts for customFees is invalid
   *
   * @generated from enum value: INVALID_CUSTOM_FEE_COLLECTOR = 233;
   */
  INVALID_CUSTOM_FEE_COLLECTOR = 233,

  /**
   * *
   * Any of the token Ids in customFees is invalid
   *
   * @generated from enum value: INVALID_TOKEN_ID_IN_CUSTOM_FEES = 234;
   */
  INVALID_TOKEN_ID_IN_CUSTOM_FEES = 234,

  /**
   * *
   * Any of the token Ids in customFees are not associated to feeCollector
   *
   * @generated from enum value: TOKEN_NOT_ASSOCIATED_TO_FEE_COLLECTOR = 235;
   */
  TOKEN_NOT_ASSOCIATED_TO_FEE_COLLECTOR = 235,

  /**
   * *
   * A token cannot have more units minted due to its configured supply ceiling
   *
   * @generated from enum value: TOKEN_MAX_SUPPLY_REACHED = 236;
   */
  TOKEN_MAX_SUPPLY_REACHED = 236,

  /**
   * *
   * The transaction attempted to move an NFT serial number from an account other than its owner
   *
   * @generated from enum value: SENDER_DOES_NOT_OWN_NFT_SERIAL_NO = 237;
   */
  SENDER_DOES_NOT_OWN_NFT_SERIAL_NO = 237,

  /**
   * *
   * A custom fee schedule entry did not specify either a fixed or fractional fee
   *
   * @generated from enum value: CUSTOM_FEE_NOT_FULLY_SPECIFIED = 238;
   */
  CUSTOM_FEE_NOT_FULLY_SPECIFIED = 238,

  /**
   * *
   * Only positive fees may be assessed at this time
   *
   * @generated from enum value: CUSTOM_FEE_MUST_BE_POSITIVE = 239;
   */
  CUSTOM_FEE_MUST_BE_POSITIVE = 239,

  /**
   * *
   * Fee schedule key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_FEE_SCHEDULE_KEY = 240;
   */
  TOKEN_HAS_NO_FEE_SCHEDULE_KEY = 240,

  /**
   * *
   * A fractional custom fee exceeded the range of a 64-bit signed integer
   *
   * @generated from enum value: CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE = 241;
   */
  CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE = 241,

  /**
   * *
   * A royalty cannot exceed the total fungible value exchanged for an NFT
   *
   * @generated from enum value: ROYALTY_FRACTION_CANNOT_EXCEED_ONE = 242;
   */
  ROYALTY_FRACTION_CANNOT_EXCEED_ONE = 242,

  /**
   * *
   * Each fractional custom fee must have its maximum_amount, if specified, at least its minimum_amount
   *
   * @generated from enum value: FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT = 243;
   */
  FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT = 243,

  /**
   * *
   * A fee schedule update tried to clear the custom fees from a token whose fee schedule was already empty
   *
   * @generated from enum value: CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES = 244;
   */
  CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES = 244,

  /**
   * *
   * Only tokens of type FUNGIBLE_COMMON can be used to as fee schedule denominations
   *
   * @generated from enum value: CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON = 245;
   */
  CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON = 245,

  /**
   * *
   * Only tokens of type FUNGIBLE_COMMON can have fractional fees
   *
   * @generated from enum value: CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 246;
   */
  CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 246,

  /**
   * *
   * The provided custom fee schedule key was invalid
   *
   * @generated from enum value: INVALID_CUSTOM_FEE_SCHEDULE_KEY = 247;
   */
  INVALID_CUSTOM_FEE_SCHEDULE_KEY = 247,

  /**
   * *
   * The requested token mint metadata was invalid
   *
   * @generated from enum value: INVALID_TOKEN_MINT_METADATA = 248;
   */
  INVALID_TOKEN_MINT_METADATA = 248,

  /**
   * *
   * The requested token burn metadata was invalid
   *
   * @generated from enum value: INVALID_TOKEN_BURN_METADATA = 249;
   */
  INVALID_TOKEN_BURN_METADATA = 249,

  /**
   * *
   * The treasury for a unique token cannot be changed until it owns no NFTs
   *
   * @generated from enum value: CURRENT_TREASURY_STILL_OWNS_NFTS = 250;
   */
  CURRENT_TREASURY_STILL_OWNS_NFTS = 250,

  /**
   * *
   * An account cannot be dissociated from a unique token if it owns NFTs for the token
   *
   * @generated from enum value: ACCOUNT_STILL_OWNS_NFTS = 251;
   */
  ACCOUNT_STILL_OWNS_NFTS = 251,

  /**
   * *
   * A NFT can only be burned when owned by the unique token's treasury
   *
   * @generated from enum value: TREASURY_MUST_OWN_BURNED_NFT = 252;
   */
  TREASURY_MUST_OWN_BURNED_NFT = 252,

  /**
   * *
   * An account did not own the NFT to be wiped
   *
   * @generated from enum value: ACCOUNT_DOES_NOT_OWN_WIPED_NFT = 253;
   */
  ACCOUNT_DOES_NOT_OWN_WIPED_NFT = 253,

  /**
   * *
   * An AccountAmount token transfers list referenced a token type other than FUNGIBLE_COMMON
   *
   * @generated from enum value: ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 254;
   */
  ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 254,

  /**
   * *
   * All the NFTs allowed in the current price regime have already been minted
   *
   * @generated from enum value: MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED = 255;
   */
  MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED = 255,

  /**
   * *
   * The payer account has been marked as deleted
   *
   * @generated from enum value: PAYER_ACCOUNT_DELETED = 256;
   */
  PAYER_ACCOUNT_DELETED = 256,

  /**
   * *
   * The reference chain of custom fees for a transferred token exceeded the maximum length of 2
   *
   * @generated from enum value: CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH = 257;
   */
  CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH = 257,

  /**
   * *
   * More than 20 balance adjustments were to satisfy a CryptoTransfer and its implied custom fee payments
   *
   * @generated from enum value: CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS = 258;
   */
  CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS = 258,

  /**
   * *
   * The sender account in the token transfer transaction could not afford a custom fee
   *
   * @generated from enum value: INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE = 259;
   */
  INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE = 259,

  /**
   * *
   * Currently no more than 4,294,967,295 NFTs may be minted for a given unique token type
   *
   * @generated from enum value: SERIAL_NUMBER_LIMIT_REACHED = 260;
   */
  SERIAL_NUMBER_LIMIT_REACHED = 260,

  /**
   * *
   * Only tokens of type NON_FUNGIBLE_UNIQUE can have royalty fees
   *
   * @generated from enum value: CUSTOM_ROYALTY_FEE_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE = 261;
   */
  CUSTOM_ROYALTY_FEE_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE = 261,

  /**
   * *
   * The account has reached the limit on the automatic associations count.
   *
   * @generated from enum value: NO_REMAINING_AUTOMATIC_ASSOCIATIONS = 262;
   */
  NO_REMAINING_AUTOMATIC_ASSOCIATIONS = 262,

  /**
   * *
   * Already existing automatic associations are more than the new maximum automatic associations.
   *
   * @generated from enum value: EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT = 263;
   */
  EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT = 263,

  /**
   * *
   * Cannot set the number of automatic associations for an account more than the maximum allowed
   * token associations <tt>tokens.maxPerAccount</tt>.
   *
   * @generated from enum value: REQUESTED_NUM_AUTOMATIC_ASSOCIATIONS_EXCEEDS_ASSOCIATION_LIMIT = 264;
   */
  REQUESTED_NUM_AUTOMATIC_ASSOCIATIONS_EXCEEDS_ASSOCIATION_LIMIT = 264,

  /**
   * *
   * Token is paused. This Token cannot be a part of any kind of Transaction until unpaused.
   *
   * @generated from enum value: TOKEN_IS_PAUSED = 265;
   */
  TOKEN_IS_PAUSED = 265,

  /**
   * *
   * Pause key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_PAUSE_KEY = 266;
   */
  TOKEN_HAS_NO_PAUSE_KEY = 266,

  /**
   * *
   * The provided pause key was invalid
   *
   * @generated from enum value: INVALID_PAUSE_KEY = 267;
   */
  INVALID_PAUSE_KEY = 267,

  /**
   * *
   * The update file in a freeze transaction body must exist.
   *
   * @generated from enum value: FREEZE_UPDATE_FILE_DOES_NOT_EXIST = 268;
   */
  FREEZE_UPDATE_FILE_DOES_NOT_EXIST = 268,

  /**
   * *
   * The hash of the update file in a freeze transaction body must match the in-memory hash.
   *
   * @generated from enum value: FREEZE_UPDATE_FILE_HASH_DOES_NOT_MATCH = 269;
   */
  FREEZE_UPDATE_FILE_HASH_DOES_NOT_MATCH = 269,

  /**
   * *
   * A FREEZE_UPGRADE transaction was handled with no previous update prepared.
   *
   * @generated from enum value: NO_UPGRADE_HAS_BEEN_PREPARED = 270;
   */
  NO_UPGRADE_HAS_BEEN_PREPARED = 270,

  /**
   * *
   * A FREEZE_ABORT transaction was handled with no scheduled freeze.
   *
   * @generated from enum value: NO_FREEZE_IS_SCHEDULED = 271;
   */
  NO_FREEZE_IS_SCHEDULED = 271,

  /**
   * *
   * The update file hash when handling a FREEZE_UPGRADE transaction differs from the file
   * hash at the time of handling the PREPARE_UPGRADE transaction.
   *
   * @generated from enum value: UPDATE_FILE_HASH_CHANGED_SINCE_PREPARE_UPGRADE = 272;
   */
  UPDATE_FILE_HASH_CHANGED_SINCE_PREPARE_UPGRADE = 272,

  /**
   * *
   * The given freeze start time was in the (consensus) past.
   *
   * @generated from enum value: FREEZE_START_TIME_MUST_BE_FUTURE = 273;
   */
  FREEZE_START_TIME_MUST_BE_FUTURE = 273,

  /**
   * *
   * The prepared update file cannot be updated or appended until either the upgrade has
   * been completed, or a FREEZE_ABORT has been handled.
   *
   * @generated from enum value: PREPARED_UPDATE_FILE_IS_IMMUTABLE = 274;
   */
  PREPARED_UPDATE_FILE_IS_IMMUTABLE = 274,

  /**
   * *
   * Once a freeze is scheduled, it must be aborted before any other type of freeze can
   * can be performed.
   *
   * @generated from enum value: FREEZE_ALREADY_SCHEDULED = 275;
   */
  FREEZE_ALREADY_SCHEDULED = 275,

  /**
   * *
   * If an NMT upgrade has been prepared, the following operation must be a FREEZE_UPGRADE.
   * (To issue a FREEZE_ONLY, submit a FREEZE_ABORT first.)
   *
   * @generated from enum value: FREEZE_UPGRADE_IN_PROGRESS = 276;
   */
  FREEZE_UPGRADE_IN_PROGRESS = 276,

  /**
   * *
   * If an NMT upgrade has been prepared, the subsequent FREEZE_UPGRADE transaction must
   * confirm the id of the file to be used in the upgrade.
   *
   * @generated from enum value: UPDATE_FILE_ID_DOES_NOT_MATCH_PREPARED = 277;
   */
  UPDATE_FILE_ID_DOES_NOT_MATCH_PREPARED = 277,

  /**
   * *
   * If an NMT upgrade has been prepared, the subsequent FREEZE_UPGRADE transaction must
   * confirm the hash of the file to be used in the upgrade.
   *
   * @generated from enum value: UPDATE_FILE_HASH_DOES_NOT_MATCH_PREPARED = 278;
   */
  UPDATE_FILE_HASH_DOES_NOT_MATCH_PREPARED = 278,

  /**
   * *
   * Consensus throttle did not allow execution of this transaction. System is throttled at
   * consensus level.
   *
   * @generated from enum value: CONSENSUS_GAS_EXHAUSTED = 279;
   */
  CONSENSUS_GAS_EXHAUSTED = 279,

  /**
   * *
   * A precompiled contract succeeded, but was later reverted.
   *
   * @generated from enum value: REVERTED_SUCCESS = 280;
   */
  REVERTED_SUCCESS = 280,

  /**
   * *
   * All contract storage allocated to the current price regime has been consumed.
   *
   * @generated from enum value: MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED = 281;
   */
  MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED = 281,

  /**
   * *
   * An alias used in a CryptoTransfer transaction is not the serialization of a primitive Key
   * message--that is, a Key with a single Ed25519 or ECDSA(secp256k1) public key and no
   * unknown protobuf fields.
   *
   * @generated from enum value: INVALID_ALIAS_KEY = 282;
   */
  INVALID_ALIAS_KEY = 282,

  /**
   * *
   * A fungible token transfer expected a different number of decimals than the involved
   * type actually has.
   *
   * @generated from enum value: UNEXPECTED_TOKEN_DECIMALS = 283;
   */
  UNEXPECTED_TOKEN_DECIMALS = 283,

  /**
   * *
   * The proxy account id is invalid or does not exist.
   *
   * @generated from enum value: INVALID_PROXY_ACCOUNT_ID = 284 [deprecated = true];
   * @deprecated
   */
  INVALID_PROXY_ACCOUNT_ID = 284,

  /**
   * *
   * The transfer account id in CryptoDelete transaction is invalid or does not exist.
   *
   * @generated from enum value: INVALID_TRANSFER_ACCOUNT_ID = 285;
   */
  INVALID_TRANSFER_ACCOUNT_ID = 285,

  /**
   * *
   * The fee collector account id in TokenFeeScheduleUpdate is invalid or does not exist.
   *
   * @generated from enum value: INVALID_FEE_COLLECTOR_ACCOUNT_ID = 286;
   */
  INVALID_FEE_COLLECTOR_ACCOUNT_ID = 286,

  /**
   * *
   * The alias already set on an account cannot be updated using CryptoUpdate transaction.
   *
   * @generated from enum value: ALIAS_IS_IMMUTABLE = 287;
   */
  ALIAS_IS_IMMUTABLE = 287,

  /**
   * *
   * An approved allowance specifies a spender account that is the same as the hbar/token
   * owner account.
   *
   * @generated from enum value: SPENDER_ACCOUNT_SAME_AS_OWNER = 288;
   */
  SPENDER_ACCOUNT_SAME_AS_OWNER = 288,

  /**
   * *
   * The establishment or adjustment of an approved allowance cause the token allowance
   * to exceed the token maximum supply.
   *
   * @generated from enum value: AMOUNT_EXCEEDS_TOKEN_MAX_SUPPLY = 289;
   */
  AMOUNT_EXCEEDS_TOKEN_MAX_SUPPLY = 289,

  /**
   * *
   * The specified amount for an approved allowance cannot be negative.
   *
   * @generated from enum value: NEGATIVE_ALLOWANCE_AMOUNT = 290;
   */
  NEGATIVE_ALLOWANCE_AMOUNT = 290,

  /**
   * *
   * The approveForAll flag cannot be set for a fungible token.
   *
   * @generated from enum value: CANNOT_APPROVE_FOR_ALL_FUNGIBLE_COMMON = 291 [deprecated = true];
   * @deprecated
   */
  CANNOT_APPROVE_FOR_ALL_FUNGIBLE_COMMON = 291,

  /**
   * *
   * The spender does not have an existing approved allowance with the hbar/token owner.
   *
   * @generated from enum value: SPENDER_DOES_NOT_HAVE_ALLOWANCE = 292;
   */
  SPENDER_DOES_NOT_HAVE_ALLOWANCE = 292,

  /**
   * *
   * The transfer amount exceeds the current approved allowance for the spender account.
   *
   * @generated from enum value: AMOUNT_EXCEEDS_ALLOWANCE = 293;
   */
  AMOUNT_EXCEEDS_ALLOWANCE = 293,

  /**
   * *
   * The payer account of an approveAllowances or adjustAllowance transaction is attempting
   * to go beyond the maximum allowed number of allowances.
   *
   * @generated from enum value: MAX_ALLOWANCES_EXCEEDED = 294;
   */
  MAX_ALLOWANCES_EXCEEDED = 294,

  /**
   * *
   * No allowances have been specified in the approval transaction.
   *
   * @generated from enum value: EMPTY_ALLOWANCES = 295;
   */
  EMPTY_ALLOWANCES = 295,

  /**
   * *
   * Spender is repeated more than once in Crypto or Token or NFT allowance lists in a single
   * CryptoApproveAllowance transaction.
   *
   * @generated from enum value: SPENDER_ACCOUNT_REPEATED_IN_ALLOWANCES = 296 [deprecated = true];
   * @deprecated
   */
  SPENDER_ACCOUNT_REPEATED_IN_ALLOWANCES = 296,

  /**
   * *
   * Serial numbers are repeated in nft allowance for a single spender account
   *
   * @generated from enum value: REPEATED_SERIAL_NUMS_IN_NFT_ALLOWANCES = 297 [deprecated = true];
   * @deprecated
   */
  REPEATED_SERIAL_NUMS_IN_NFT_ALLOWANCES = 297,

  /**
   * *
   * Fungible common token used in NFT allowances
   *
   * @generated from enum value: FUNGIBLE_TOKEN_IN_NFT_ALLOWANCES = 298;
   */
  FUNGIBLE_TOKEN_IN_NFT_ALLOWANCES = 298,

  /**
   * *
   * Non fungible token used in fungible token allowances
   *
   * @generated from enum value: NFT_IN_FUNGIBLE_TOKEN_ALLOWANCES = 299;
   */
  NFT_IN_FUNGIBLE_TOKEN_ALLOWANCES = 299,

  /**
   * *
   * The account id specified as the owner is invalid or does not exist.
   *
   * @generated from enum value: INVALID_ALLOWANCE_OWNER_ID = 300;
   */
  INVALID_ALLOWANCE_OWNER_ID = 300,

  /**
   * *
   * The account id specified as the spender is invalid or does not exist.
   *
   * @generated from enum value: INVALID_ALLOWANCE_SPENDER_ID = 301;
   */
  INVALID_ALLOWANCE_SPENDER_ID = 301,

  /**
   * *
   * [Deprecated] If the CryptoDeleteAllowance transaction has repeated crypto or token or Nft allowances to delete.
   *
   * @generated from enum value: REPEATED_ALLOWANCES_TO_DELETE = 302 [deprecated = true];
   * @deprecated
   */
  REPEATED_ALLOWANCES_TO_DELETE = 302,

  /**
   * *
   * If the account Id specified as the delegating spender is invalid or does not exist.
   *
   * @generated from enum value: INVALID_DELEGATING_SPENDER = 303;
   */
  INVALID_DELEGATING_SPENDER = 303,

  /**
   * *
   * The delegating Spender cannot grant approveForAll allowance on a NFT token type for another spender.
   *
   * @generated from enum value: DELEGATING_SPENDER_CANNOT_GRANT_APPROVE_FOR_ALL = 304;
   */
  DELEGATING_SPENDER_CANNOT_GRANT_APPROVE_FOR_ALL = 304,

  /**
   * *
   * The delegating Spender cannot grant allowance on a NFT serial for another spender as it doesnt not have approveForAll
   * granted on token-owner.
   *
   * @generated from enum value: DELEGATING_SPENDER_DOES_NOT_HAVE_APPROVE_FOR_ALL = 305;
   */
  DELEGATING_SPENDER_DOES_NOT_HAVE_APPROVE_FOR_ALL = 305,

  /**
   * *
   * The scheduled transaction could not be created because it's expiration_time was too far in the future.
   *
   * @generated from enum value: SCHEDULE_EXPIRATION_TIME_TOO_FAR_IN_FUTURE = 306;
   */
  SCHEDULE_EXPIRATION_TIME_TOO_FAR_IN_FUTURE = 306,

  /**
   * *
   * The scheduled transaction could not be created because it's expiration_time was less than or equal to the consensus time.
   *
   * @generated from enum value: SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME = 307;
   */
  SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME = 307,

  /**
   * *
   * The scheduled transaction could not be created because it would cause throttles to be violated on the specified expiration_time.
   *
   * @generated from enum value: SCHEDULE_FUTURE_THROTTLE_EXCEEDED = 308;
   */
  SCHEDULE_FUTURE_THROTTLE_EXCEEDED = 308,

  /**
   * *
   * The scheduled transaction could not be created because it would cause the gas limit to be violated on the specified expiration_time.
   *
   * @generated from enum value: SCHEDULE_FUTURE_GAS_LIMIT_EXCEEDED = 309;
   */
  SCHEDULE_FUTURE_GAS_LIMIT_EXCEEDED = 309,

  /**
   * *
   * The ethereum transaction either failed parsing or failed signature validation, or some other EthereumTransaction error not covered by another response code.
   *
   * @generated from enum value: INVALID_ETHEREUM_TRANSACTION = 310;
   */
  INVALID_ETHEREUM_TRANSACTION = 310,

  /**
   * *
   * EthereumTransaction was signed against a chainId that this network does not support.
   *
   * @generated from enum value: WRONG_CHAIN_ID = 311;
   */
  WRONG_CHAIN_ID = 311,

  /**
   * *
   * This transaction specified an ethereumNonce that is not the current ethereumNonce of the account.
   *
   * @generated from enum value: WRONG_NONCE = 312;
   */
  WRONG_NONCE = 312,

  /**
   * *
   * The ethereum transaction specified an access list, which the network does not support.
   *
   * @generated from enum value: ACCESS_LIST_UNSUPPORTED = 313;
   */
  ACCESS_LIST_UNSUPPORTED = 313,

  /**
   * *
   * A schedule being signed or deleted has passed it's expiration date and is pending execution if needed and then expiration.
   *
   * @generated from enum value: SCHEDULE_PENDING_EXPIRATION = 314;
   */
  SCHEDULE_PENDING_EXPIRATION = 314,

  /**
   * *
   * A selfdestruct or ContractDelete targeted a contract that is a token treasury.
   *
   * @generated from enum value: CONTRACT_IS_TOKEN_TREASURY = 315;
   */
  CONTRACT_IS_TOKEN_TREASURY = 315,

  /**
   * *
   * A selfdestruct or ContractDelete targeted a contract with non-zero token balances.
   *
   * @generated from enum value: CONTRACT_HAS_NON_ZERO_TOKEN_BALANCES = 316;
   */
  CONTRACT_HAS_NON_ZERO_TOKEN_BALANCES = 316,

  /**
   * *
   * A contract referenced by a transaction is "detached"; that is, expired and lacking any
   * hbar funds for auto-renewal payment---but still within its post-expiry grace period.
   *
   * @generated from enum value: CONTRACT_EXPIRED_AND_PENDING_REMOVAL = 317;
   */
  CONTRACT_EXPIRED_AND_PENDING_REMOVAL = 317,

  /**
   * *
   * A ContractUpdate requested removal of a contract's auto-renew account, but that contract has
   * no auto-renew account.
   *
   * @generated from enum value: CONTRACT_HAS_NO_AUTO_RENEW_ACCOUNT = 318;
   */
  CONTRACT_HAS_NO_AUTO_RENEW_ACCOUNT = 318,

  /**
   * *
   * A delete transaction submitted via HAPI set permanent_removal=true
   *
   * @generated from enum value: PERMANENT_REMOVAL_REQUIRES_SYSTEM_INITIATION = 319;
   */
  PERMANENT_REMOVAL_REQUIRES_SYSTEM_INITIATION = 319,

  /**
   *
   * A CryptoCreate or ContractCreate used the deprecated proxyAccountID field.
   *
   * @generated from enum value: PROXY_ACCOUNT_ID_FIELD_IS_DEPRECATED = 320;
   */
  PROXY_ACCOUNT_ID_FIELD_IS_DEPRECATED = 320,

  /**
   * *
   * An account set the staked_account_id to itself in CryptoUpdate or ContractUpdate transactions.
   *
   * @generated from enum value: SELF_STAKING_IS_NOT_ALLOWED = 321;
   */
  SELF_STAKING_IS_NOT_ALLOWED = 321,

  /**
   * *
   * The staking account id or staking node id given is invalid or does not exist.
   *
   * @generated from enum value: INVALID_STAKING_ID = 322;
   */
  INVALID_STAKING_ID = 322,

  /**
   * *
   * Native staking, while implemented, has not yet enabled by the council.
   *
   * @generated from enum value: STAKING_NOT_ENABLED = 323;
   */
  STAKING_NOT_ENABLED = 323,

  /**
   * *
   * The range provided in UtilPrng transaction is negative.
   *
   * @generated from enum value: INVALID_PRNG_RANGE = 324;
   */
  INVALID_PRNG_RANGE = 324,

  /**
   * *
   * The maximum number of entities allowed in the current price regime have been created.
   *
   * @generated from enum value: MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED = 325;
   */
  MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED = 325,

  /**
   * *
   * The full prefix signature for precompile is not valid
   *
   * @generated from enum value: INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE = 326;
   */
  INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE = 326,

  /**
   * *
   * The combined balances of a contract and its auto-renew account (if any) did not cover
   * the rent charged for net new storage used in a transaction.
   *
   * @generated from enum value: INSUFFICIENT_BALANCES_FOR_STORAGE_RENT = 327;
   */
  INSUFFICIENT_BALANCES_FOR_STORAGE_RENT = 327,

  /**
   * *
   * A contract transaction tried to use more than the allowed number of child records, via
   * either system contract records or internal contract creations.
   *
   * @generated from enum value: MAX_CHILD_RECORDS_EXCEEDED = 328;
   */
  MAX_CHILD_RECORDS_EXCEEDED = 328,

  /**
   * *
   * The combined balances of a contract and its auto-renew account (if any) or balance of an account did not cover
   * the auto-renewal fees in a transaction.
   *
   * @generated from enum value: INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES = 329;
   */
  INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES = 329,

  /**
   * *
   * A transaction's protobuf message includes unknown fields; could mean that a client
   * expects not-yet-released functionality to be available.
   *
   * @generated from enum value: TRANSACTION_HAS_UNKNOWN_FIELDS = 330;
   */
  TRANSACTION_HAS_UNKNOWN_FIELDS = 330,

  /**
   * *
   * The account cannot be modified. Account's key is not set
   *
   * @generated from enum value: ACCOUNT_IS_IMMUTABLE = 331;
   */
  ACCOUNT_IS_IMMUTABLE = 331,

  /**
   * *
   * An alias that is assigned to an account or contract cannot be assigned to another account or contract.
   *
   * @generated from enum value: ALIAS_ALREADY_ASSIGNED = 332;
   */
  ALIAS_ALREADY_ASSIGNED = 332,

  /**
   * *
   * A provided metadata key was invalid. Verification includes, for example, checking the size of Ed25519 and ECDSA(secp256k1) public keys.
   *
   * @generated from enum value: INVALID_METADATA_KEY = 333;
   */
  INVALID_METADATA_KEY = 333,

  /**
   * *
   * Metadata key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_METADATA_KEY = 334;
   */
  TOKEN_HAS_NO_METADATA_KEY = 334,

  /**
   * *
   * Token Metadata is not provided
   *
   * @generated from enum value: MISSING_TOKEN_METADATA = 335;
   */
  MISSING_TOKEN_METADATA = 335,

  /**
   * *
   * NFT serial numbers are missing in the TokenUpdateNftsTransactionBody
   *
   * @generated from enum value: MISSING_SERIAL_NUMBERS = 336;
   */
  MISSING_SERIAL_NUMBERS = 336,

  /**
   * *
   * Admin key is not set on token
   *
   * @generated from enum value: TOKEN_HAS_NO_ADMIN_KEY = 337;
   */
  TOKEN_HAS_NO_ADMIN_KEY = 337,

  /**
   * *
   * A transaction failed because the consensus node identified is
   * deleted from the address book.
   *
   * @generated from enum value: NODE_DELETED = 338;
   */
  NODE_DELETED = 338,

  /**
   * *
   * A transaction failed because the consensus node identified is not valid or
   * does not exist in state.
   *
   * @generated from enum value: INVALID_NODE_ID = 339;
   */
  INVALID_NODE_ID = 339,

  /**
   * *
   * A transaction failed because one or more entries in the list of
   * service endpoints for the `gossip_endpoint` field is invalid.<br/>
   * The most common cause for this response is a service endpoint that has
   * the domain name (DNS) set rather than address and port.
   *
   * @generated from enum value: INVALID_GOSSIP_ENDPOINT = 340;
   */
  INVALID_GOSSIP_ENDPOINT = 340,

  /**
   * *
   * A transaction failed because the node account identifier provided
   * does not exist or is not valid.<br/>
   * One common source of this error is providing a node account identifier
   * using the "alias" form rather than "numeric" form.
   * It is also used for atomic batch transaction for child transaction if the node account id is not 0.0.0.
   *
   * @generated from enum value: INVALID_NODE_ACCOUNT_ID = 341;
   */
  INVALID_NODE_ACCOUNT_ID = 341,

  /**
   * *
   * A transaction failed because the description field cannot be encoded
   * as UTF-8 or is more than 100 bytes when encoded.
   *
   * @generated from enum value: INVALID_NODE_DESCRIPTION = 342;
   */
  INVALID_NODE_DESCRIPTION = 342,

  /**
   * *
   * A transaction failed because one or more entries in the list of
   * service endpoints for the `service_endpoint` field is invalid.<br/>
   * The most common cause for this response is a service endpoint that has
   * the domain name (DNS) set rather than address and port.
   *
   * @generated from enum value: INVALID_SERVICE_ENDPOINT = 343;
   */
  INVALID_SERVICE_ENDPOINT = 343,

  /**
   * *
   * A transaction failed because the TLS certificate provided for the
   * node is missing or invalid.
   * <p>
   * #### Probable Causes
   * The certificate MUST be a TLS certificate of a type permitted for gossip
   * signatures.<br/>
   * The value presented MUST be a UTF-8 NFKD encoding of the TLS
   * certificate.<br/>
   * The certificate encoded MUST be in PEM format.<br/>
   * The `gossip_ca_certificate` field is REQUIRED and MUST NOT be empty.
   *
   * @generated from enum value: INVALID_GOSSIP_CA_CERTIFICATE = 344;
   */
  INVALID_GOSSIP_CA_CERTIFICATE = 344,

  /**
   * *
   * A transaction failed because the hash provided for the gRPC certificate
   * is present but invalid.
   * <p>
   * #### Probable Causes
   * The `grpc_certificate_hash` MUST be a SHA-384 hash.<br/>
   * The input hashed MUST be a UTF-8 NFKD encoding of the actual TLS
   * certificate.<br/>
   * The certificate to be encoded MUST be in PEM format.
   *
   * @generated from enum value: INVALID_GRPC_CERTIFICATE = 345;
   */
  INVALID_GRPC_CERTIFICATE = 345,

  /**
   * *
   * The maximum automatic associations value is not valid.<br/>
   * The most common cause for this error is a value less than `-1`.
   *
   * @generated from enum value: INVALID_MAX_AUTO_ASSOCIATIONS = 346;
   */
  INVALID_MAX_AUTO_ASSOCIATIONS = 346,

  /**
   * *
   * The maximum number of nodes allowed in the address book have been created.
   *
   * @generated from enum value: MAX_NODES_CREATED = 347;
   */
  MAX_NODES_CREATED = 347,

  /**
   * *
   * In ServiceEndpoint, domain_name and ipAddressV4 are mutually exclusive
   *
   * @generated from enum value: IP_FQDN_CANNOT_BE_SET_FOR_SAME_ENDPOINT = 348;
   */
  IP_FQDN_CANNOT_BE_SET_FOR_SAME_ENDPOINT = 348,

  /**
   * *
   *  Fully qualified domain name is not allowed in gossip_endpoint
   *
   * @generated from enum value: GOSSIP_ENDPOINT_CANNOT_HAVE_FQDN = 349;
   */
  GOSSIP_ENDPOINT_CANNOT_HAVE_FQDN = 349,

  /**
   * *
   * In ServiceEndpoint, domain_name size too large
   *
   * @generated from enum value: FQDN_SIZE_TOO_LARGE = 350;
   */
  FQDN_SIZE_TOO_LARGE = 350,

  /**
   * *
   * ServiceEndpoint is invalid
   *
   * @generated from enum value: INVALID_ENDPOINT = 351;
   */
  INVALID_ENDPOINT = 351,

  /**
   * *
   * The number of gossip endpoints exceeds the limit
   *
   * @generated from enum value: GOSSIP_ENDPOINTS_EXCEEDED_LIMIT = 352;
   */
  GOSSIP_ENDPOINTS_EXCEEDED_LIMIT = 352,

  /**
   * *
   * The transaction attempted to use duplicate `TokenReference`.<br/>
   * This affects `TokenReject` attempting to reject same token reference more than once.
   *
   * @generated from enum value: TOKEN_REFERENCE_REPEATED = 353;
   */
  TOKEN_REFERENCE_REPEATED = 353,

  /**
   * *
   * The account id specified as the owner in `TokenReject` is invalid or does not exist.
   *
   * @generated from enum value: INVALID_OWNER_ID = 354;
   */
  INVALID_OWNER_ID = 354,

  /**
   * *
   * The transaction attempted to use more than the allowed number of `TokenReference`.
   *
   * @generated from enum value: TOKEN_REFERENCE_LIST_SIZE_LIMIT_EXCEEDED = 355;
   */
  TOKEN_REFERENCE_LIST_SIZE_LIMIT_EXCEEDED = 355,

  /**
   * *
   * The number of service endpoints exceeds the limit
   *
   * @generated from enum value: SERVICE_ENDPOINTS_EXCEEDED_LIMIT = 356;
   */
  SERVICE_ENDPOINTS_EXCEEDED_LIMIT = 356,

  /**
   *
   * The IPv4 address is invalid
   *
   * @generated from enum value: INVALID_IPV4_ADDRESS = 357;
   */
  INVALID_IPV4_ADDRESS = 357,

  /**
   * *
   * The transaction attempted to use empty `TokenReference` list.
   *
   * @generated from enum value: EMPTY_TOKEN_REFERENCE_LIST = 358;
   */
  EMPTY_TOKEN_REFERENCE_LIST = 358,

  /**
   *
   * The node account is not allowed to be updated
   *
   * @generated from enum value: UPDATE_NODE_ACCOUNT_NOT_ALLOWED = 359;
   */
  UPDATE_NODE_ACCOUNT_NOT_ALLOWED = 359,

  /**
   *
   * The token has no metadata or supply key
   *
   * @generated from enum value: TOKEN_HAS_NO_METADATA_OR_SUPPLY_KEY = 360;
   */
  TOKEN_HAS_NO_METADATA_OR_SUPPLY_KEY = 360,

  /**
   * *
   * The list of `PendingAirdropId`s is empty and MUST NOT be empty.
   *
   * @generated from enum value: EMPTY_PENDING_AIRDROP_ID_LIST = 361;
   */
  EMPTY_PENDING_AIRDROP_ID_LIST = 361,

  /**
   * *
   * A `PendingAirdropId` is repeated in a `claim` or `cancel` transaction.
   *
   * @generated from enum value: PENDING_AIRDROP_ID_REPEATED = 362;
   */
  PENDING_AIRDROP_ID_REPEATED = 362,

  /**
   * *
   * The number of `PendingAirdropId` values in the list exceeds the maximum
   * allowable number.
   *
   * @generated from enum value: PENDING_AIRDROP_ID_LIST_TOO_LONG = 363;
   */
  PENDING_AIRDROP_ID_LIST_TOO_LONG = 363,

  /**
   *
   * A pending airdrop already exists for the specified NFT.
   *
   * @generated from enum value: PENDING_NFT_AIRDROP_ALREADY_EXISTS = 364;
   */
  PENDING_NFT_AIRDROP_ALREADY_EXISTS = 364,

  /**
   *
   * The identified account is sender for one or more pending airdrop(s)
   * and cannot be deleted.
   * <p>
   * The requester SHOULD cancel all pending airdrops before resending
   * this transaction.
   *
   * @generated from enum value: ACCOUNT_HAS_PENDING_AIRDROPS = 365;
   */
  ACCOUNT_HAS_PENDING_AIRDROPS = 365,

  /**
   * *
   * Consensus throttle did not allow execution of this transaction.<br/>
   * The transaction should be retried after a modest delay.
   *
   * @generated from enum value: THROTTLED_AT_CONSENSUS = 366;
   */
  THROTTLED_AT_CONSENSUS = 366,

  /**
   * *
   * The provided pending airdrop id is invalid.<br/>
   * This pending airdrop MAY already be claimed or cancelled.
   * <p>
   * The client SHOULD query a mirror node to determine the current status of
   * the pending airdrop.
   *
   * @generated from enum value: INVALID_PENDING_AIRDROP_ID = 367;
   */
  INVALID_PENDING_AIRDROP_ID = 367,

  /**
   * *
   * The token to be airdropped has a fallback royalty fee and cannot be
   * sent or claimed via an airdrop transaction.
   *
   * @generated from enum value: TOKEN_AIRDROP_WITH_FALLBACK_ROYALTY = 368;
   */
  TOKEN_AIRDROP_WITH_FALLBACK_ROYALTY = 368,

  /**
   * *
   * This airdrop claim is for a pending airdrop with an invalid token.<br/>
   * The token might be deleted, or the sender may not have enough tokens
   * to fulfill the offer.
   * <p>
   * The client SHOULD query mirror node to determine the status of the
   * pending airdrop and whether the sender can fulfill the offer.
   *
   * @generated from enum value: INVALID_TOKEN_IN_PENDING_AIRDROP = 369;
   */
  INVALID_TOKEN_IN_PENDING_AIRDROP = 369,

  /**
   * *
   * A scheduled transaction configured to wait for expiry to execute was given
   * an expiry time at which there is already too many transactions scheduled to
   * expire; its creation must be retried with a different expiry.
   *
   * @generated from enum value: SCHEDULE_EXPIRY_IS_BUSY = 370;
   */
  SCHEDULE_EXPIRY_IS_BUSY = 370,

  /**
   * *
   * The provided gRPC certificate hash is invalid.
   *
   * @generated from enum value: INVALID_GRPC_CERTIFICATE_HASH = 371;
   */
  INVALID_GRPC_CERTIFICATE_HASH = 371,

  /**
   * *
   * A scheduled transaction configured to wait for expiry to execute was not
   * given an explicit expiration time.
   *
   * @generated from enum value: MISSING_EXPIRY_TIME = 372;
   */
  MISSING_EXPIRY_TIME = 372,

  /**
   * *
   * A contract operation attempted to schedule another transaction after it
   * had already scheduled a recursive contract call.
   *
   * @generated from enum value: NO_SCHEDULING_ALLOWED_AFTER_SCHEDULED_RECURSION = 373;
   */
  NO_SCHEDULING_ALLOWED_AFTER_SCHEDULED_RECURSION = 373,

  /**
   * *
   * A contract can schedule recursive calls a finite number of times (this is
   * approximately four million times with typical network configuration.)
   *
   * @generated from enum value: RECURSIVE_SCHEDULING_LIMIT_REACHED = 374;
   */
  RECURSIVE_SCHEDULING_LIMIT_REACHED = 374,

  /**
   * *
   * The target network is waiting for the ledger ID to be set, which is a
   * side effect of finishing the network's TSS construction.
   *
   * @generated from enum value: WAITING_FOR_LEDGER_ID = 375;
   */
  WAITING_FOR_LEDGER_ID = 375,

  /**
   * *
   * The provided fee exempt key list size exceeded the limit.
   *
   * @generated from enum value: MAX_ENTRIES_FOR_FEE_EXEMPT_KEY_LIST_EXCEEDED = 376;
   */
  MAX_ENTRIES_FOR_FEE_EXEMPT_KEY_LIST_EXCEEDED = 376,

  /**
   * *
   * The provided fee exempt key list contains duplicated keys.
   *
   * @generated from enum value: FEE_EXEMPT_KEY_LIST_CONTAINS_DUPLICATED_KEYS = 377;
   */
  FEE_EXEMPT_KEY_LIST_CONTAINS_DUPLICATED_KEYS = 377,

  /**
   * *
   * The provided fee exempt key list contains an invalid key.
   *
   * @generated from enum value: INVALID_KEY_IN_FEE_EXEMPT_KEY_LIST = 378;
   */
  INVALID_KEY_IN_FEE_EXEMPT_KEY_LIST = 378,

  /**
   * *
   * The provided fee schedule key contains an invalid key.
   *
   * @generated from enum value: INVALID_FEE_SCHEDULE_KEY = 379;
   */
  INVALID_FEE_SCHEDULE_KEY = 379,

  /**
   * *
   * If a fee schedule key is not set when we create a topic
   * we cannot add it on update.
   *
   * @generated from enum value: FEE_SCHEDULE_KEY_CANNOT_BE_UPDATED = 380;
   */
  FEE_SCHEDULE_KEY_CANNOT_BE_UPDATED = 380,

  /**
   * *
   * If the topic's custom fees are updated the topic SHOULD have a
   * fee schedule key
   *
   * @generated from enum value: FEE_SCHEDULE_KEY_NOT_SET = 381;
   */
  FEE_SCHEDULE_KEY_NOT_SET = 381,

  /**
   * *
   * The fee amount is exceeding the amount that the payer
   * is willing to pay.
   *
   * @generated from enum value: MAX_CUSTOM_FEE_LIMIT_EXCEEDED = 382;
   */
  MAX_CUSTOM_FEE_LIMIT_EXCEEDED = 382,

  /**
   * *
   * There are no corresponding custom fees.
   *
   * @generated from enum value: NO_VALID_MAX_CUSTOM_FEE = 383;
   */
  NO_VALID_MAX_CUSTOM_FEE = 383,

  /**
   * *
   * The provided list contains invalid max custom fee.
   *
   * @generated from enum value: INVALID_MAX_CUSTOM_FEES = 384;
   */
  INVALID_MAX_CUSTOM_FEES = 384,

  /**
   * *
   * The provided max custom fee list contains fees with
   * duplicate denominations.
   *
   * @generated from enum value: DUPLICATE_DENOMINATION_IN_MAX_CUSTOM_FEE_LIST = 385;
   */
  DUPLICATE_DENOMINATION_IN_MAX_CUSTOM_FEE_LIST = 385,

  /**
   * *
   * The provided max custom fee list contains fees with
   * duplicate account id.
   *
   * @generated from enum value: DUPLICATE_ACCOUNT_ID_IN_MAX_CUSTOM_FEE_LIST = 386;
   */
  DUPLICATE_ACCOUNT_ID_IN_MAX_CUSTOM_FEE_LIST = 386,

  /**
   * *
   * Max custom fees list is not supported for this operation.
   *
   * @generated from enum value: MAX_CUSTOM_FEES_IS_NOT_SUPPORTED = 387;
   */
  MAX_CUSTOM_FEES_IS_NOT_SUPPORTED = 387,

  /**
   * *
   * The list of batch transactions is empty
   *
   * @generated from enum value: BATCH_LIST_EMPTY = 388;
   */
  BATCH_LIST_EMPTY = 388,

  /**
   * *
   * The list of batch transactions contains duplicated transactions
   *
   * @generated from enum value: BATCH_LIST_CONTAINS_DUPLICATES = 389;
   */
  BATCH_LIST_CONTAINS_DUPLICATES = 389,

  /**
   * *
   * The list of batch transactions contains a transaction type that is
   * in the AtomicBatch blacklist as configured in the network.
   *
   * @generated from enum value: BATCH_TRANSACTION_IN_BLACKLIST = 390;
   */
  BATCH_TRANSACTION_IN_BLACKLIST = 390,

  /**
   * *
   * The inner transaction of a batch transaction failed
   *
   * @generated from enum value: INNER_TRANSACTION_FAILED = 391;
   */
  INNER_TRANSACTION_FAILED = 391,

  /**
   * *
   * The inner transaction of a batch transaction is missing a batch key
   *
   * @generated from enum value: MISSING_BATCH_KEY = 392;
   */
  MISSING_BATCH_KEY = 392,

  /**
   * *
   * The batch key is set for a non batch transaction
   *
   * @generated from enum value: BATCH_KEY_SET_ON_NON_INNER_TRANSACTION = 393;
   */
  BATCH_KEY_SET_ON_NON_INNER_TRANSACTION = 393,

  /**
   * *
   * The batch key is not valid
   *
   * @generated from enum value: INVALID_BATCH_KEY = 394;
   */
  INVALID_BATCH_KEY = 394,

  /**
   * *
   * The provided schedule expiry time is not configurable.
   *
   * @generated from enum value: SCHEDULE_EXPIRY_NOT_CONFIGURABLE = 395;
   */
  SCHEDULE_EXPIRY_NOT_CONFIGURABLE = 395,

  /**
   * *
   * The network just started at genesis and is creating system entities.
   *
   * @generated from enum value: CREATING_SYSTEM_ENTITIES = 396;
   */
  CREATING_SYSTEM_ENTITIES = 396,

  /**
   * *
   * The least common multiple of the throttle group's milliOpsPerSec is
   * too large and it's overflowing.
   *
   * @generated from enum value: THROTTLE_GROUP_LCM_OVERFLOW = 397;
   */
  THROTTLE_GROUP_LCM_OVERFLOW = 397,

  /**
   * *
   * Token airdrop transactions can not contain multiple senders for a single token.
   *
   * @generated from enum value: AIRDROP_CONTAINS_MULTIPLE_SENDERS_FOR_A_TOKEN = 398;
   */
  AIRDROP_CONTAINS_MULTIPLE_SENDERS_FOR_A_TOKEN = 398,

  /**
   * *
   * The GRPC proxy endpoint is set in the NodeCreate or NodeUpdate transaction,
   * which the network does not support.
   *
   * @generated from enum value: GRPC_WEB_PROXY_NOT_SUPPORTED = 399;
   */
  GRPC_WEB_PROXY_NOT_SUPPORTED = 399,

  /**
   * *
   * An NFT transfers list referenced a token type other than NON_FUNGIBLE_UNIQUE.
   *
   * @generated from enum value: NFT_TRANSFERS_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE = 400;
   */
  NFT_TRANSFERS_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE = 400,
}

/**
 * Describes the enum proto.ResponseCodeEnum.
 */
export declare const ResponseCodeEnumSchema: GenEnum<ResponseCodeEnum>;

