//*
// gRPC service definitions for Hedera.
// Message types imported from common.proto.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file services.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import type { QuerySchema, ResponseSchema, TransactionResponseSchema, TransactionSchema } from "./common_pb.js";

/**
 * Describes the file services.proto.
 */
export declare const file_services: GenFile;

/**
 * @generated from service proto.CryptoService
 */
export declare const CryptoService: GenService<{
  /**
   * @generated from rpc proto.CryptoService.createAccount
   */
  createAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.updateAccount
   */
  updateAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.cryptoTransfer
   */
  cryptoTransfer: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.cryptoDelete
   */
  cryptoDelete: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.approveAllowances
   */
  approveAllowances: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.deleteAllowances
   */
  deleteAllowances: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.addLiveHash
   */
  addLiveHash: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.deleteLiveHash
   */
  deleteLiveHash: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getLiveHash
   */
  getLiveHash: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getAccountRecords
   */
  getAccountRecords: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.cryptoGetBalance
   */
  cryptoGetBalance: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getAccountInfo
   */
  getAccountInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getTransactionReceipts
   */
  getTransactionReceipts: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getFastTransactionRecord
   */
  getFastTransactionRecord: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getTxRecordByTxID
   */
  getTxRecordByTxID: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.CryptoService.getStakersByAccountID
   */
  getStakersByAccountID: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
}>;

/**
 * @generated from service proto.SmartContractService
 */
export declare const SmartContractService: GenService<{
  /**
   * @generated from rpc proto.SmartContractService.createContract
   */
  createContract: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.updateContract
   */
  updateContract: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.contractCallMethod
   */
  contractCallMethod: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.getContractInfo
   */
  getContractInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.contractCallLocalMethod
   */
  contractCallLocalMethod: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.ContractGetBytecode
   */
  contractGetBytecode: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.getBySolidityID
   */
  getBySolidityID: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.getTxRecordByContractID
   */
  getTxRecordByContractID: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.deleteContract
   */
  deleteContract: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.systemDelete
   */
  systemDelete: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.systemUndelete
   */
  systemUndelete: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.SmartContractService.callEthereum
   */
  callEthereum: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

/**
 * @generated from service proto.FileService
 */
export declare const FileService: GenService<{
  /**
   * @generated from rpc proto.FileService.createFile
   */
  createFile: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.updateFile
   */
  updateFile: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.deleteFile
   */
  deleteFile: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.appendContent
   */
  appendContent: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.getFileContent
   */
  getFileContent: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.getFileInfo
   */
  getFileInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.systemDelete
   */
  systemDelete: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.FileService.systemUndelete
   */
  systemUndelete: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

/**
 * @generated from service proto.ConsensusService
 */
export declare const ConsensusService: GenService<{
  /**
   * @generated from rpc proto.ConsensusService.createTopic
   */
  createTopic: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.ConsensusService.updateTopic
   */
  updateTopic: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.ConsensusService.deleteTopic
   */
  deleteTopic: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.ConsensusService.getTopicInfo
   */
  getTopicInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.ConsensusService.submitMessage
   */
  submitMessage: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

/**
 * @generated from service proto.FreezeService
 */
export declare const FreezeService: GenService<{
  /**
   * @generated from rpc proto.FreezeService.freeze
   */
  freeze: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

/**
 * @generated from service proto.NetworkService
 */
export declare const NetworkService: GenService<{
  /**
   * @generated from rpc proto.NetworkService.getVersionInfo
   */
  getVersionInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.NetworkService.getExecutionTime
   */
  getExecutionTime: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.NetworkService.uncheckedSubmit
   */
  uncheckedSubmit: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.NetworkService.getAccountDetails
   */
  getAccountDetails: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
}>;

/**
 * @generated from service proto.TokenService
 */
export declare const TokenService: GenService<{
  /**
   * @generated from rpc proto.TokenService.createToken
   */
  createToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.updateToken
   */
  updateToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.mintToken
   */
  mintToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.burnToken
   */
  burnToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.deleteToken
   */
  deleteToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.wipeTokenAccount
   */
  wipeTokenAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.freezeTokenAccount
   */
  freezeTokenAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.unfreezeTokenAccount
   */
  unfreezeTokenAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.grantKycToTokenAccount
   */
  grantKycToTokenAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.revokeKycFromTokenAccount
   */
  revokeKycFromTokenAccount: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.associateTokens
   */
  associateTokens: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.dissociateTokens
   */
  dissociateTokens: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.updateTokenFeeSchedule
   */
  updateTokenFeeSchedule: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.getTokenInfo
   */
  getTokenInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.getAccountNftInfos
   */
  getAccountNftInfos: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.getTokenNftInfo
   */
  getTokenNftInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.getTokenNftInfos
   */
  getTokenNftInfos: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.pauseToken
   */
  pauseToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.unpauseToken
   */
  unpauseToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.updateNfts
   */
  updateNfts: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.rejectToken
   */
  rejectToken: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.airdropTokens
   */
  airdropTokens: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.cancelAirdrop
   */
  cancelAirdrop: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.TokenService.claimAirdrop
   */
  claimAirdrop: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

/**
 * @generated from service proto.ScheduleService
 */
export declare const ScheduleService: GenService<{
  /**
   * @generated from rpc proto.ScheduleService.createSchedule
   */
  createSchedule: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.ScheduleService.signSchedule
   */
  signSchedule: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.ScheduleService.deleteSchedule
   */
  deleteSchedule: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.ScheduleService.getScheduleInfo
   */
  getScheduleInfo: {
    methodKind: "unary";
    input: typeof QuerySchema;
    output: typeof ResponseSchema;
  },
}>;

/**
 * @generated from service proto.UtilService
 */
export declare const UtilService: GenService<{
  /**
   * @generated from rpc proto.UtilService.prng
   */
  prng: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

/**
 * @generated from service proto.AddressBookService
 */
export declare const AddressBookService: GenService<{
  /**
   * @generated from rpc proto.AddressBookService.createNode
   */
  createNode: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.AddressBookService.deleteNode
   */
  deleteNode: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
  /**
   * @generated from rpc proto.AddressBookService.updateNode
   */
  updateNode: {
    methodKind: "unary";
    input: typeof TransactionSchema;
    output: typeof TransactionResponseSchema;
  },
}>;

