//*
// # Timestamp
// Messages to describe exact date-time values, with resolution of seconds or
// nanoseconds, referenced to the UNIX epoch.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file timestamp.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file timestamp.proto.
 */
export const file_timestamp = /*@__PURE__*/
  fileDesc("Cg90aW1lc3RhbXAucHJvdG8SBXByb3RvIisKCVRpbWVzdGFtcBIPCgdzZWNvbmRzGAEgASgDEg0KBW5hbm9zGAIgASgFIiMKEFRpbWVzdGFtcFNlY29uZHMSDwoHc2Vjb25kcxgBIAEoA0ImCiJjb20uaGVkZXJhaGFzaGdyYXBoLmFwaS5wcm90by5qYXZhUAFiBnByb3RvMw");

/**
 * Describes the message proto.Timestamp.
 * Use `create(TimestampSchema)` to create a new message.
 */
export const TimestampSchema = /*@__PURE__*/
  messageDesc(file_timestamp, 0);

/**
 * Describes the message proto.TimestampSeconds.
 * Use `create(TimestampSecondsSchema)` to create a new message.
 */
export const TimestampSecondsSchema = /*@__PURE__*/
  messageDesc(file_timestamp, 1);

