//*
// # Timestamp
// Messages to describe exact date-time values, with resolution of seconds or
// nanoseconds, referenced to the UNIX epoch.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file timestamp.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file timestamp.proto.
 */
export declare const file_timestamp: GenFile;

/**
 * *
 * An exact date and time.<br/>
 * This is the same data structure as the Google protobuf Timestamp.proto.
 *
 * #### Additional Notes
 * Useful information is present in comments on the
 * [Google version](https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto).
 *
 * @generated from message proto.Timestamp
 */
export declare type Timestamp = Message<"proto.Timestamp"> & {
  /**
   * *
   * The number of complete seconds since the start of the epoch.
   * <p>
   * For this purpose, `epoch` SHALL be the UNIX epoch with 0
   * at `1970-01-01T00:00:00.000Z`.<br/>
   * This value MUST be greater than 0.<br/>
   * This value SHOULD be strictly greater than `946684800`.
   *
   * @generated from field: int64 seconds = 1;
   */
  seconds: bigint;

  /**
   * *
   * The number of nanoseconds after the start of the second referenced
   * in `seconds`.
   * <p>
   * This value MUST be greater than or equal to 0.<br/>
   * This value MUST be strictly less than 1,000,000,000.
   *
   * @generated from field: int32 nanos = 2;
   */
  nanos: number;
};

/**
 * Describes the message proto.Timestamp.
 * Use `create(TimestampSchema)` to create a new message.
 */
export declare const TimestampSchema: GenMessage<Timestamp>;

/**
 * *
 * An exact date and time, with a resolution of one second.
 *
 * @generated from message proto.TimestampSeconds
 */
export declare type TimestampSeconds = Message<"proto.TimestampSeconds"> & {
  /**
   * *
   * The number of complete seconds since the start of the epoch.
   * <p>
   * For this purpose, `epoch` SHALL be the UNIX epoch with 0
   * at `1970-01-01T00:00:00.000Z`.<br/>
   * This value MUST be greater than 0.<br/>
   * This value SHOULD be strictly greater than `946684800`.
   *
   * @generated from field: int64 seconds = 1;
   */
  seconds: bigint;
};

/**
 * Describes the message proto.TimestampSeconds.
 * Use `create(TimestampSecondsSchema)` to create a new message.
 */
export declare const TimestampSecondsSchema: GenMessage<TimestampSeconds>;

