//*
// Token info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file token_info.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AccountID, Key, TokenFreezeStatus, TokenID, TokenKycStatus, TokenPauseStatus, TokenSupplyType, TokenType } from "./basic_types_pb.js";
import type { Duration } from "./duration_pb.js";
import type { Timestamp } from "./timestamp_pb.js";
import type { CustomFee } from "./custom_fees_pb.js";

/**
 * Describes the file token_info.proto.
 */
export declare const file_token_info: GenFile;

/**
 * @generated from message proto.TokenInfo
 */
export declare type TokenInfo = Message<"proto.TokenInfo"> & {
  /**
   * @generated from field: proto.TokenID tokenId = 1;
   */
  tokenId?: TokenID;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string symbol = 3;
   */
  symbol: string;

  /**
   * @generated from field: uint32 decimals = 4;
   */
  decimals: number;

  /**
   * @generated from field: uint64 totalSupply = 5;
   */
  totalSupply: bigint;

  /**
   * @generated from field: proto.AccountID treasury = 6;
   */
  treasury?: AccountID;

  /**
   * @generated from field: proto.Key adminKey = 7;
   */
  adminKey?: Key;

  /**
   * @generated from field: proto.Key kycKey = 8;
   */
  kycKey?: Key;

  /**
   * @generated from field: proto.Key freezeKey = 9;
   */
  freezeKey?: Key;

  /**
   * @generated from field: proto.Key wipeKey = 10;
   */
  wipeKey?: Key;

  /**
   * @generated from field: proto.Key supplyKey = 11;
   */
  supplyKey?: Key;

  /**
   * @generated from field: proto.TokenFreezeStatus defaultFreezeStatus = 12;
   */
  defaultFreezeStatus: TokenFreezeStatus;

  /**
   * @generated from field: proto.TokenKycStatus defaultKycStatus = 13;
   */
  defaultKycStatus: TokenKycStatus;

  /**
   * @generated from field: bool deleted = 14;
   */
  deleted: boolean;

  /**
   * @generated from field: proto.AccountID autoRenewAccount = 15;
   */
  autoRenewAccount?: AccountID;

  /**
   * @generated from field: proto.Duration autoRenewPeriod = 16;
   */
  autoRenewPeriod?: Duration;

  /**
   * @generated from field: proto.Timestamp expiry = 17;
   */
  expiry?: Timestamp;

  /**
   * @generated from field: string memo = 18;
   */
  memo: string;

  /**
   * @generated from field: proto.TokenType tokenType = 19;
   */
  tokenType: TokenType;

  /**
   * @generated from field: proto.TokenSupplyType supplyType = 20;
   */
  supplyType: TokenSupplyType;

  /**
   * @generated from field: int64 maxSupply = 21;
   */
  maxSupply: bigint;

  /**
   * @generated from field: proto.Key fee_schedule_key = 22;
   */
  feeScheduleKey?: Key;

  /**
   * @generated from field: repeated proto.CustomFee custom_fees = 23;
   */
  customFees: CustomFee[];

  /**
   * @generated from field: proto.Key pause_key = 24;
   */
  pauseKey?: Key;

  /**
   * @generated from field: proto.TokenPauseStatus pause_status = 25;
   */
  pauseStatus: TokenPauseStatus;

  /**
   * @generated from field: string ledger_id = 26;
   */
  ledgerId: string;

  /**
   * @generated from field: bytes metadata = 27;
   */
  metadata: Uint8Array;

  /**
   * @generated from field: proto.Key metadata_key = 28;
   */
  metadataKey?: Key;
};

/**
 * Describes the message proto.TokenInfo.
 * Use `create(TokenInfoSchema)` to create a new message.
 */
export declare const TokenInfoSchema: GenMessage<TokenInfo>;

