//*
// Token info query response types.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file token_info.proto (package proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_basic_types } from "./basic_types_pb.js";
import { file_timestamp } from "./timestamp_pb.js";
import { file_duration } from "./duration_pb.js";
import { file_custom_fees } from "./custom_fees_pb.js";

/**
 * Describes the file token_info.proto.
 */
export const file_token_info = /*@__PURE__*/
  fileDesc("ChB0b2tlbl9pbmZvLnByb3RvEgVwcm90byLvBgoJVG9rZW5JbmZvEh8KB3Rva2VuSWQYASABKAsyDi5wcm90by5Ub2tlbklEEgwKBG5hbWUYAiABKAkSDgoGc3ltYm9sGAMgASgJEhAKCGRlY2ltYWxzGAQgASgNEhMKC3RvdGFsU3VwcGx5GAUgASgEEiIKCHRyZWFzdXJ5GAYgASgLMhAucHJvdG8uQWNjb3VudElEEhwKCGFkbWluS2V5GAcgASgLMgoucHJvdG8uS2V5EhoKBmt5Y0tleRgIIAEoCzIKLnByb3RvLktleRIdCglmcmVlemVLZXkYCSABKAsyCi5wcm90by5LZXkSGwoHd2lwZUtleRgKIAEoCzIKLnByb3RvLktleRIdCglzdXBwbHlLZXkYCyABKAsyCi5wcm90by5LZXkSNQoTZGVmYXVsdEZyZWV6ZVN0YXR1cxgMIAEoDjIYLnByb3RvLlRva2VuRnJlZXplU3RhdHVzEi8KEGRlZmF1bHRLeWNTdGF0dXMYDSABKA4yFS5wcm90by5Ub2tlbkt5Y1N0YXR1cxIPCgdkZWxldGVkGA4gASgIEioKEGF1dG9SZW5ld0FjY291bnQYDyABKAsyEC5wcm90by5BY2NvdW50SUQSKAoPYXV0b1JlbmV3UGVyaW9kGBAgASgLMg8ucHJvdG8uRHVyYXRpb24SIAoGZXhwaXJ5GBEgASgLMhAucHJvdG8uVGltZXN0YW1wEgwKBG1lbW8YEiABKAkSIwoJdG9rZW5UeXBlGBMgASgOMhAucHJvdG8uVG9rZW5UeXBlEioKCnN1cHBseVR5cGUYFCABKA4yFi5wcm90by5Ub2tlblN1cHBseVR5cGUSEQoJbWF4U3VwcGx5GBUgASgDEiQKEGZlZV9zY2hlZHVsZV9rZXkYFiABKAsyCi5wcm90by5LZXkSJQoLY3VzdG9tX2ZlZXMYFyADKAsyEC5wcm90by5DdXN0b21GZWUSHQoJcGF1c2Vfa2V5GBggASgLMgoucHJvdG8uS2V5Ei0KDHBhdXNlX3N0YXR1cxgZIAEoDjIXLnByb3RvLlRva2VuUGF1c2VTdGF0dXMSEQoJbGVkZ2VyX2lkGBogASgJEhAKCG1ldGFkYXRhGBsgASgMEiAKDG1ldGFkYXRhX2tleRgcIAEoCzIKLnByb3RvLktleUImCiJjb20uaGVkZXJhaGFzaGdyYXBoLmFwaS5wcm90by5qYXZhUAFiBnByb3RvMw", [file_basic_types, file_timestamp, file_duration, file_custom_fees]);

/**
 * Describes the message proto.TokenInfo.
 * Use `create(TokenInfoSchema)` to create a new message.
 */
export const TokenInfoSchema = /*@__PURE__*/
  messageDesc(file_token_info, 0);

