import { wrapSchema } from "./wrapper.js";
import {
    FreezeTypeSchema,
    FreezeType,
    HookIdSchema,
    HookEntityIdSchema,
    HookCallSchema,
    EvmHookCallSchema,
} from "../minimal_gen/misc_types_pb.js";
import {
    ShardIDSchema,
    RealmIDSchema,
    TokenIDSchema,
    AccountIDSchema,
    NftIDSchema,
    FileIDSchema,
    ContractIDSchema,
    TopicIDSchema,
    ScheduleIDSchema,
    TransactionIDSchema,
    AccountAmountSchema,
    TransferListSchema,
    NftTransferSchema,
    TokenTransferListSchema,
    FractionSchema,
    KeySchema,
    ThresholdKeySchema,
    KeyListSchema,
    SignatureSchema,
    ThresholdSignatureSchema,
    SignatureListSchema,
    SignatureMapSchema,
    SignaturePairSchema,
    FeeComponentsSchema,
    FeeDataSchema,
    FeeScheduleSchema,
    TransactionFeeScheduleSchema,
    CurrentAndNextFeeScheduleSchema,
    ServiceEndpointSchema,
    NodeAddressSchema,
    NodeAddressBookSchema,
    SemanticVersionSchema,
    SettingSchema,
    ServicesConfigurationListSchema,
    TokenRelationshipSchema,
    TokenBalanceSchema,
    TokenBalancesSchema,
    TokenAssociationSchema,
    StakingInfoSchema,
    PendingAirdropIdSchema,
    PendingAirdropValueSchema,
    BlockHashAlgorithm,
    TokenType,
    SubType,
    TokenSupplyType,
    TokenKeyValidation,
    TokenFreezeStatus,
    TokenKycStatus,
    TokenPauseStatus,
    HederaFunctionality,
} from "../minimal_gen/basic_types_pb.js";
import { TimestampSchema, TimestampSecondsSchema } from "../minimal_gen/timestamp_pb.js";

export const proto = {
    ShardID: wrapSchema(ShardIDSchema),
    RealmID: wrapSchema(RealmIDSchema),
    TokenID: wrapSchema(TokenIDSchema),
    AccountID: wrapSchema(AccountIDSchema),
    NftID: wrapSchema(NftIDSchema),
    FileID: wrapSchema(FileIDSchema),
    ContractID: wrapSchema(ContractIDSchema),
    TopicID: wrapSchema(TopicIDSchema),
    ScheduleID: wrapSchema(ScheduleIDSchema),
    TransactionID: wrapSchema(TransactionIDSchema),
    AccountAmount: wrapSchema(AccountAmountSchema),
    TransferList: wrapSchema(TransferListSchema),
    NftTransfer: wrapSchema(NftTransferSchema),
    TokenTransferList: wrapSchema(TokenTransferListSchema),
    Fraction: wrapSchema(FractionSchema),
    Key: wrapSchema(KeySchema),
    ThresholdKey: wrapSchema(ThresholdKeySchema),
    KeyList: wrapSchema(KeyListSchema),
    Signature: wrapSchema(SignatureSchema),
    ThresholdSignature: wrapSchema(ThresholdSignatureSchema),
    SignatureList: wrapSchema(SignatureListSchema),
    SignatureMap: wrapSchema(SignatureMapSchema),
    SignaturePair: wrapSchema(SignaturePairSchema),
    FeeComponents: wrapSchema(FeeComponentsSchema),
    FeeData: wrapSchema(FeeDataSchema),
    FeeSchedule: wrapSchema(FeeScheduleSchema),
    TransactionFeeSchedule: wrapSchema(TransactionFeeScheduleSchema),
    CurrentAndNextFeeSchedule: wrapSchema(CurrentAndNextFeeScheduleSchema),
    ServiceEndpoint: wrapSchema(ServiceEndpointSchema),
    NodeAddress: wrapSchema(NodeAddressSchema),
    NodeAddressBook: wrapSchema(NodeAddressBookSchema),
    SemanticVersion: wrapSchema(SemanticVersionSchema),
    Setting: wrapSchema(SettingSchema),
    ServicesConfigurationList: wrapSchema(ServicesConfigurationListSchema),
    TokenRelationship: wrapSchema(TokenRelationshipSchema),
    TokenBalance: wrapSchema(TokenBalanceSchema),
    TokenBalances: wrapSchema(TokenBalancesSchema),
    TokenAssociation: wrapSchema(TokenAssociationSchema),
    StakingInfo: wrapSchema(StakingInfoSchema),
    PendingAirdropId: wrapSchema(PendingAirdropIdSchema),
    PendingAirdropValue: wrapSchema(PendingAirdropValueSchema),
    HookId: wrapSchema(HookIdSchema),
    HookEntityId: wrapSchema(HookEntityIdSchema),
    HookCall: wrapSchema(HookCallSchema),
    EvmHookCall: wrapSchema(EvmHookCallSchema),
    Timestamp: wrapSchema(TimestampSchema),
    TimestampSeconds: wrapSchema(TimestampSecondsSchema),
    BlockHashAlgorithm,
    TokenType,
    SubType,
    TokenSupplyType,
    TokenKeyValidation,
    TokenFreezeStatus,
    TokenKycStatus,
    TokenPauseStatus,
    HederaFunctionality,
    FreezeType,
};
