name: 'Slack Release Notification'
on:
  release:
    types:
      - published

env:
  js-sdk-channel-id: C0958RN2ZTR

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  notify-slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.js-sdk-channel-id }}",
              "text": ":js-release: New release published: ${{ github.event.release.tag_name }} — <${{ github.event.release.html_url }}|View release>"
            }
