name: 'Slack Release Notification'
on:
  release:
    types:
      - published

env:
  js-sdk-channel-id: C0958RN2ZTR

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  notify-slack:
    name: Notify Slack
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.js-sdk-channel-id }}",
              "text": ":js-release: New release published: ${{ github.event.release.tag_name }} — <${{ github.event.release.html_url }}|View release>"
            }
